# Lecture 3 {#lec3}
**Monday, January 25, 1993**

Given graphs $\Gamma = (X, E)$ and $\Gamma' = (X', E')$.


:::{.example}
$\Delta = \{a, a^{-1}\}$

```{r echo=FALSE, fig.width=2, fig.height=1.5, message=FALSE, fig.align="center"}
library(tidyverse)
df_eg31 <- data.frame(x = c(0, 0.5, 1.5, 2, 1.5, 0.5, 0), y = c(0, -1, -1, 0, 1, 1, 0))
ggplot(df_eg31, aes(x, y)) + geom_point() + geom_path() + theme_bw() + theme(panel.border = element_blank(),line = element_blank(),
        text = element_blank(),
        title = element_blank()) +
  annotate("text", x=-0.25, y = 0, label = "1") + annotate("text", x=0.33, y = -1, label = "a") +
  annotate("text", x=1.7, y = -0.95, label = "a^2", parse = TRUE) + annotate("text", x=2.2, y = 0, label = "a^3", parse = TRUE) +
  annotate("text", x=0.30, y = 1, label = "a^{-1}", parse = TRUE) + annotate("text", x=1.8, y = 0.98, label = "a^{-2}", parse = TRUE)
```
:::


:::{.example}
$\Delta = \{a, a^{-1}, a^2, a^{-2}\}$

```{r echo=FALSE, fig.width=2, fig.height=1.5, message=FALSE, fig.align="center"}
library(tidyverse)
df_eg32 <- data.frame(x = c(0, 0.5, 1.5, 2, 1.5, 0.5, 0.5, 2, 0.5, 0, 1.5, 1.5, 0), y = c(0, -1, -1, 0, 1, 1, -1, 0, 1, 0, -1, 1, 0))
ggplot(df_eg32, aes(x, y)) + geom_point() + geom_path() + theme_bw() + theme(panel.border = element_blank(),line = element_blank(),
        text = element_blank(),
        title = element_blank()) +
  annotate("text", x=-0.25, y = 0, label = "1") + annotate("text", x=0.33, y = -1, label = "a") +
  annotate("text", x=1.7, y = -0.95, label = "a^2", parse = TRUE) + annotate("text", x=2.2, y = 0, label = "a^3", parse = TRUE) +
  annotate("text", x=0.30, y = 1, label = "a^{-1}", parse = TRUE) + annotate("text", x=1.8, y = 0.98, label = "a^{-2}", parse = TRUE)
```
:::

:::{.example}
$G = \langle a, b \mid a^6 = 1, b^2, ab = ba\rangle$, $\Delta = \{a, a^{-1}, b\}$

```{r echo=FALSE, fig.width=3.5, fig.height=2.5, message=FALSE, fig.align="center", warning = FALSE}
library(tidyverse)
df_eg32 <- data.frame(x = c(0, 1, 3, 4, 3, 1, 0, 0.8, 1.5, 1, 1.5, 1.5, 2.5, 3, 2.5, 2.5, 3.2, 4, 3.2, 3.2, 2.5, 3, 2.5,2.5, 1.5, 1, 1.5, 1.5, 0.8), y = c(0, -1.5, -1.5, 0, 1.5, 1.5, 0, 0, -1, -1.5, NA, -1, -1, -1.5, NA, -1, 0, 0, NA, 0, 1, 1.5, NA, 1, 1, 1.5, NA, 1, 0))
ggplot(df_eg32, aes(x, y)) + geom_point() + geom_path() + theme_bw() + theme(panel.border = element_blank(),line = element_blank(),
        text = element_blank(),
        title = element_blank()) +
  annotate("text", x=-0.2, y = 0, label = "b") + annotate("text", x=1.6, y = -0.9, label = "a") +
  annotate("text", x=0.8, y = -1.5, label = "ab") + annotate("text", x=0.6, y = 1.56, label = "a^{-1}", parse = TRUE) +
  annotate("text", x=0.8, y = 1.53, label = "b") + annotate("text", x=3.2, y = -1.5, label = "a^2", parse = TRUE) +
  annotate("text", x=3.35, y = -1.53, label = "b") + annotate("text", x=3.2, y = 1.55, label = "a^{-2}", parse = TRUE) +
  annotate("text", x=3.39, y = 1.53, label = "b") +
  annotate("text", x=2.4, y = -0.85, label = "a^2", parse = TRUE) + annotate("text", x=1, y = 0, label = "1", parse = TRUE) +
  annotate("text", x=3, y = 0, label = "a^3", parse = TRUE) + annotate("text", x=4.2, y = 0, label = paste0("a^{3}"), parse=TRUE) +
  annotate("text", x=4.36, y = -0.02, label = paste0("b"), parse=TRUE) +
  annotate("text", x=1.6, y = 0.85, label = "a^{-1}", parse = TRUE) + annotate("text", x=2.4, y = 0.85, label = "a^{-2}", parse = TRUE)
```
:::
