# $T$-Modules of $H(D,2)$, I {#lec5}
**Friday, January 29, 1993**

Let $\Gamma = (X, E)$ be a graph, $A$ the adjacency matrix, and $V$ the standard module over $K = \mathbb{C}$.

Fix a base $x\in X$ and write $E_i^* \equiv E_i^*(x)$, and $T \equiv T(x)$. 

Let $W$ be an irreducible $T$-module with endpoint $r:= \min\{i\mid E_i^*W \neq 0\}$ and diameter $d:=|\{i\mid E_i^*W\neq 0\}|-1$. 

We have 
\begin{align}
{E^*_i}W & \neq 0 & r\leq i \leq r+d\\
& = 0 & 0 \leq i < r \;\text{ or }\; r+d < i \leq d(x).
\end{align}

Claim: $E_i^*AE_j^*W \neq 0$ if $|i-j| = 1$ for $r\leq i,j\leq r+d$. (See Lemma \@ref(lem:irreducible).)

Suppose $E_{j+1}^*AE_j^*W = 0$ for some $j$ with $r \leq j < r+d$.
Observe that
$$\tilde{W} = E^*_rW + \cdots + E^*_jW$$
is $T$-invariant with 
$$0 \subsetneq \tilde{W} \subsetneq W.$$
Becase $A\tilde{W} \subseteq \tilde{W}$ since $AE_j^*W \subseteq E^*_{j-1}W + E^*_jW$, 
$$E_k^*\tilde{W} \subseteq \tilde{W} \quad\text{for all }\; k,$$
we have $T\tilde{W} \subseteq{W}$.

Suppose $E_{i-1}^*AE_i^*W = 0$ for some $i$ with $r \leq i < r+d$. 

Similarly,
$$\tilde{W} = E^*_iW + \cdots + E^*_{r+d}W$$
is a $T$-module with $0\subsetneq \tilde{W} \subsetneq W$.

:::{.definition #isomorphic-modules}
Let $\Gamma$, $E^*_i$, and $T$ be as above. Irreducible $T$-modules $W$ and $W'$ are isomorphic\index{isomorphic} whenever there is an isomorphism $\sigma: W \to W'$ of vector spaces such that $a\sigma = \sigma a$ for all $a\in T$. 
:::

Recall that the standard module $V$ is an orthogonal direct sum of irreducible $T$-modules 
$$W_1 \oplus W_2 \oplus \cdots \oplus W_{\ell}, \; \text{for some }\ell.$$ 
Given $W$ in this list, the multiplicity\index{multiplicity} of $W$ in $V$ is 
$$|\{j \mid W_j \simeq W\}|.$$

:::{.hs}
**HS MEMO**

It is known that the multiplicity does not depend on the decomposition.
:::

Now assume that $\Gamma$ is the $D$-cube, $H(D,2)$ with $D\geq 1$. View 
\begin{align}
X & = \{a_1\cdots a_D\mid a_i\in \{1, -1\}, 1\leq i\leq D\},\\
E & = \{xy\mid x, y\in X, \; x, y \;\text{ differ in exactly 1 coordinate}\}.
\end{align}
Find $T$-modules.

Claim: $H(D,2)$ is bipartite with a partition $X = X^+ \cup X^-$, where
\begin{align}
X^+ & = \{a_1\cdots a_D\in X\mid \prod a_i > 0\}\\
X^- & = \{a_1\cdots a_D \in X \mid \prod a_i < 0\}
\end{align}

Observe: for all $y, z\in X$, 
$$\partial(y,z) = i \Leftrightarrow y, z \; \text{ differ in exactly in }\; i\; \text{ coorinates with }\; 0\leq i\leq D.$$
Here, the diameter of $H(D, 2) = D = d$ for all $x\in X$.

:::{.theorem #hd2-modules}
Let $\Gamma = H(D,2)$ be as above. Fix $x\in X$, and write $E_i^* = E^*_i(x)$, and $T = T(x)$. 

Let $W$ be an irreducible $T$-module with endpoint $r$, and diameter $d$ with $0\leq r \leq r+d\leq D$.

| $(i)$ $W$ has a basis $w_0, w_1, \ldots, w_d$ with $w_i\in E^*_{i+r}W$ for $0\leq i\leq d$. With respect to which the matrix representing $A$ is 
$$
\begin{pmatrix}
0 & d & 0 & \cdots & 0 & 0 & 0\\
1 & 0 & d-1 & \cdots & 0 & 0 & 0\\
0 & 2 & 0 & \cdots & 0 & 0 & 0\\
0 & 0 & 3 & \cdots & 0 & 0 & 0\\
\cdots & \cdots & \cdots & \ddots & \ddots & \cdots & \cdots \\
0 & 0 & 0 & \ddots & 0 & 2 & 0\\
0 & 0 & 0 & \cdots & d-1 & 0 & 1\\
0 & 0 & 0 & \cdots & 0 & d & 0
\end{pmatrix}
$$

| $(ii)$ $d= D-2r$. In particular, $0\leq r\leq D/2$.

| $(iii)$ Let $W'$ denote an irreducible $T$-module with endpoint $r'$. Then $W$ and $W'$ are isormorphic as $T$-modules if and only if $r = r'$.

| $(iv)$ The multiplicity of the irreducible $T$-module with endpoint $r$ is 
$$\binom{D}{r} - \binom{D}{r-1} \quad \text{if } 1\leq r \leq R/2,$$
and $1$ if $r = 0$.
:::

:::{.proof}
Recall that $\Gamma$ is vertex transitive. It is a Cayley graph.

Hence without loss of generality, we may assume that 
$x = \overbrace{11\cdots 1}^{D}$.

Notation: Set $\Omega = \{1, 2, \ldots, D\}$. For every subset $S \subseteq \Omega$, let 
$$\hat{S} = a_1\cdots a_d \in X \quad a_i = \begin{cases} -1 & \text{if }\; i\in S\\ 1 & \text{if } i\not\in S.\end{cases}$$
In particular, $\hat{\emptyset} = x$ and 
$$|S| = i \Leftrightarrow \partial(x, \hat{S}) = i \Leftrightarrow \hat{S}\in E^*_iV.$$
For all $S, T\subseteq \Omega$, we say $S$ covers $T$ if and only if $S\supseteq T$ and $|S| = |T| +1$.

Observe that $\hat{S}, \hat{T}$ are adjacent in $\Gamma$ if and only if either $T$ coverse $S$ or $S$ coverr $T$.

Define the 'raising matrix'
$$R = \sum_{i=0}^D E^*_{i+1}AE^*_i.$$

Observe that
$$RE_i^*V \subseteq E^*_{i+1} V \; \text{ for }\; 0\leq i \leq D, \; \text{ and }E^*_{D+1}V = 0.$$
Indeed for any $S\subseteq \Omega$ with $|S| = i$,
\begin{align}
R\hat{S} & = RE^*_i\hat{S} \\
& = E^*_{i+1}A\hat{S} \\
& = \sum_{T_1 \subseteq \Omega, S \text{ covers }T_1} E^*_{i+1}\widehat{T_1} + \sum_{T \subseteq \Omega, T \text{ covers }S} E^*_{i+1}\hat{T}\\
& = \sum_{T \subseteq \Omega, T \text{ covers }S} E^*_{i+1}\hat{T}.
\end{align}

Define the 'lowering matrix'
$$L = \sum_{i=0}^D E^*_{i-1}AE^*_i.$$

Observe that
$$LE_i^*V \subseteq E^*_{i-1}V \; \text{ for }\; 0\leq i \leq D, \; \text{ and }E^*_{-1}V = 0.$$
Indeed for any $S\subseteq \Omega$,
$$L\hat{S} = \sum_{T\subseteq \Omega, S \text{ covers }T} \hat{T}.$$

Observe that $A = L + R$.

For convenience, set
$$A^* = \sum_{i=0}^D (D-2i)E_i^*.$$

Claim: The following hold.

| $(a)$ $LR - RL = A^*$.
| $(b)$ $A^*L - LA^* = 2L$.
| $(c)$ $A^*R - RA^* = -2R$.

In particular $\mathrm{Span}(R,L, A^*)$ is a 'representation of Lie algebra $\mathrm{sl}_2(\mathbb{C})$.


:::{.hs name="Lie Algebra sl2(C)"}
**HS MEMO**

$$\mathrm{sl}_2(\mathbb{C}) = \{X\mid \mathrm{Mat}(\mathbb{C} \mid \mathrm{tr}(X) = 0\}.$$
For $X, Y\in \mathrm{sl}_2(\mathbb{C})$, define a binary operation $[X, Y] = XY - YX$.
$$A^*\sim \begin{pmatrix} 1 & 0 \\ 0 & -1\end{pmatrix}, \quad L\sim \begin{pmatrix} 0 & 1 \\ 0 & 0\end{pmatrix}, \quad R\sim \begin{pmatrix} 0 & 0 \\ 1 & 0\end{pmatrix}.$$
Then these satisfy the relations $(a)$ - $(c)$ above.
:::

_Proof of Claim._
Apply both sides to $\hat{S}$ \quad $(S\subseteq \Omega)$. Say $|S| = i$.

_Proof of $(a)$:_
\begin{align} 
(LR - RL)\hat{S} & = L\left(\sum_{\substack{T \subseteq \Omega, T \text{ covers }S\\(D-i \text{ of them})}}\hat{T}\right) - R \left(\sum_{\substack{U \subseteq \Omega, S \text{ covers }U\\(i \text{ of them})}}\hat{U}\right)\\
& = (D-i)\hat{S} + \sum_{V \subseteq \Omega, |V| = i, |S\cap V| = i-1}\hat{V}\\
& \qquad - \left(i\hat{S} + \sum_{V \subseteq \Omega, |V| = i, |S\cap V| = i-1}\hat{V}\right)\\
& = (D-2i)\hat{S}\\
& = A^*\hat{S}.
\end{align}

_Proof of $(b)$:_
\begin{align} 
(A^*L - LA^*)\hat{S} & = (D-2(i-1))L\hat{S} - (D-2i)L\hat{S} \quad (\text{since} \; L\hat{S}\in E^*_{i-1}V)\\
& = 2L\hat{S}.
\end{align}

_Proof of $(c)$:_
\begin{align} 
(A^*R - RA^*)\hat{S} & = (D-2(i+1))R\hat{S} - (D-2i)R\hat{S} \quad (\text{since} \; R\hat{S}\in E^*_{i+1}V)\\
& = -2R\hat{S}.
\end{align}

Let $W$ be an irreducible $T$-module with endpoint $r$ and diameter $d$ $(0\leq r \leq r+d \leq D)$.

_Proof of $(i)$ and $(ii)$:_

Pick $0\neq w \in E^*_rW$.

Claim: $LRw = (D-2r)w$.

_Pf._ 
\begin{align} 
LRw & = (A^*+RL)w \quad (\text{by Claim }(a))\\
& = A^*w \quad (Lw \in E^*_{r-1}W = 0)\\
& = (D-2r)w.
\end{align}
Define
$$w_i = \frac{1}{i!}R^iw \in E^*_{r+i}W \quad (0\leq i \leq d).$$
Then,
\begin{align}
Rw_i & = (i+1)w_{i+1}\quad (0\leq i \leq d)\\
Rw_d & = 0 \quad (\text{by definition of }d)
\end{align}

Claim: $Lw_0 = 0$ and 
$$Lw_i = (D-2r-i+1)w_{i-1} \quad (1\leq i\leq d).$$

_Pf._ We prove by induction on $i$.
The case $i=0$ is trivial, and the case $i=1$ follows from above claim. 
Let $i\geq 2$, 
\begin{align}
Lw_i & = \frac{1}{i}LRw_{i-1} = \frac{1}{i}(A^*+RL)w_{i-1} \quad (\text{by Claim (a)})\\
& \quad \text{(by induction hypothesis)}\\
& = \frac{1}{i}((D-2(r+i-1))w_{i-1} + (D-2r-(i-1)+1)Rw_{i-2} \quad (Rw_{i-2} = (i-1)w_{i-1})\\
& = \frac{1}{i}i(D-2r-i+1)w_{i-1}\\
& = (D-2r-i+1)w_{i-1}.
\end{align}

Claim: $w_0, \ldots, w_d$ is a basis for $W$.

_Pf._ 
Let $W' = \mathrm{Span}\{w_0, \ldots, w_d\}$. Then $W'$ is $R$ and $L$ invariant. So it is $A = R+L$ invariant. 

Also it is $E^*_i$-invariant for every $i$. 

Hence $W'$ is a $T$-module. 

Since $W$ is irreducible, $W' = W$.

As $w_i$'s are orthogonal, theyy are linearly independent. Note that $w_i\neq 0$ by the definition of $d$ and Lemma \@ref(lem:irreducible) $(iv)$.

Claim: $d = D-2r$.

_Pf._ 
By $(a)$,
\begin{align}
0 & = (LR - RL - A^*)w_d \\
& = 0 - (D-2r-d+1)Rw_{d-1} - (D-2(r+d))w_d\\
& = -d(D-2r-d+1)w_d - (D-2(r+d))w_d\\
& = (-dD + 2rd + d^2 - d - D + 2r + 2d)w_d\\
& = (d^2 + (2r-D+1)d + 2r - D)w_d\\
& = (d+2r-D)(d+1)w_d.
\end{align}
Hence $d = D-2r$.

Therefore, with respect to a bais $w_0, w_1, \ldots, w_d$, 
$A = L+R$, $w_{-1} = w_{d+1} = 0$,
$$Lw_i = (d-i+1)w_{i-1}, \quad Rw_i = (i+1)w_{i+1}.$$
$$L = \begin{pmatrix} 0 & d & 0 & \cdots & 0 & 0\\
0 & 0 & d-1 & \cdots & 0 & 0\\
\vdots & \vdots & \ddots & \ddots & \vdots & \vdots \\
\vdots & \vdots & \cdots & \cdots & 0 & 1\\
0 & 0 & 0 & \cdots & 0 & 0
\end{pmatrix}, \qquad 
R = \begin{pmatrix} 0 & 0 & 0 & \cdots & 0 & 0\\
1 & 0 & 0 & \cdots & 0 & 0\\
0 & 2 & 0 & \cdots & \vdots & \vdots\\
\vdots & \vdots & \ddots  & \ddots & 0 & 1\\
0 & 0 & 0 & \cdots & d & 0
\end{pmatrix}.$$
This completes the proof of $(i)$ and $(ii)$.
:::
