# Thin Graphs {#lec8}
**Friday, February 5, 1993**

:::{.proof name="Proof of Theorem \@ref(thm:thin-condition) continued"}
| (S) $\Rightarrow$ (C)
Fix $i$ and pick $a, b\in E_i^*TE_i^*$. 

Since $a$, $b$ and $ab$ are symmetric, 
$$ab = (ab)^\top = b^\top a^\top = ba.$$
Hence $E_i^*TE_i^*$ is commutative. 

| (G) $\Rightarrow$ (S)
Fix $i$ and pick $a \in E_i^*TE_i^*$. Pick vertices $y, z\in X$. 

We want to show that 
$$a_{yz} = a_{zy}.$$
We may assume that 
$$\partial(x, y) = \partial(x,z) = i,$$
otherwise 
$$a_{yz} = a_{zy} = 0.$$
By our assumption, there exists $g\in G$ such that
$$g(y) = z, \quad g(z) = y, \quad g(x) = x.$$
Let $\hat{g}$ denote the permutation matrix representing $g$, i.e., 
$$\hat{g}\hat{y} =\widehat{g(y)} \quad \text{for all }\ y\in X, \quad \hat{y} = \begin{pmatrix}0\\\vdots \\ 1 \\\vdots \\0\end{pmatrix}\begin{matrix} \\ \\ \leftarrow y \\ \\ \text{ } \end{matrix}.$$
If $g\in \mathrm{Aut}(\Gamma)$, then
$$\hat{g}A = A\hat{g} \quad \text{(Exercise)}.$$
Also, we have 
$$\hat{g}E_j^* = E^*_j\hat{g} \quad (0\leq j\leq D),$$
since 
$$\partial(x,y) = \partial(g(x), g(y)) = \partial(x, g(y)).$$
Hence, $\hat{g}$ commutes with each element of $T$. We have
\begin{align}
a_{yz} & = (\hat{g}^{-1}a\hat{g})_{yz}, \quad (\hat{g})_{yz} = \begin{cases} 1 & g(z) = y\\ 0 & \text{else.}\end{cases}\\
& = \sum_{y', z'}(\hat{g}^{-1})_{yy'}a_{y'z'}\hat{g}_{z'z}\\
& \quad (\text{zero except for $g^{-1}(y') = y, \; g(z) = z'$}.)\\
& = a_{g(y)g(z)}\\
& = a_{zy}.
\end{align}
This proves Theorem  \@ref(thm:thin-condition).
:::


**Open Problem:**
Find all the graphs that satisfy the condition (G) for every vertex $x$.

$H(N, 2)$ is one example, because
$$\mathrm{Aut}\Gamma_{1\cdots 1} \simeq S_\Omega, \quad x = (1\cdots 1), \quad \Gamma_i(x) = \{\hat{S} \mid |S| = i\}.$$

Property (G) is clearly related to the distance-transitive property.

:::{.definition}
Let $\Gamma = (X, E)$ be any graph. $\Gamma$ with $G\subseteq \mathrm{Aut}(\Gamma)$ is said to be distance-transitive \index{distance-transitive} (or two-point homogeneous), whenever 
$$\text{for all } x, x', y, y'\in X \; \text{ with } \partial(x,y) = \partial(x',y'),$$ 
there exists $g\in G$ such that
$$g(x) = x',\quad g(y) = y'.$$
(This means $G$ is as close to being doubly transitive as possible.)
:::

:::{.lemma #property-g}
Suppose a graph $\Gamma = (X, E)$ satisfies the property \textrm{(G) = (G($x$))} for every $x\in X$. Then, 

| $(i)$ either
| $\quad (ia)$ $\Gamma$ is vertex transitive; or
| $\quad (iia)$ $\Gamma$ is bipartite $(X = X^+ \cup X^-)$ with $X^+$, $X^-$ each an orbit of $\mathrm{Aut}(\Gamma)$.

| $(ii)$ if $(ia)$ holds, then $\Gamma$ is distance-transitive.
:::

:::{.proof}
$(i)$
Claim. Suppose $y, z\in X$ are conneced by a path of even length. Then $y, z$ are in the same orbit of $\mathrm{Aut}(\Gamma)$.

_Pf of Claim._ 
It suffices to assume that the path has lenght $2$, $y \sim w\sim z$. 

Now $\partial(y,w) = \partial(w,z) = 1$. So there exits $g\in \mathrm{Aut}(\Gamma)$ such that 
$$gw = w, \quad gy = z, \quad gz = y.$$
This proves Claim.

Fix $x\in X$. Now suppose that $\Gamma$ is not vertex transitive, and we shall show $(ib)$.

Observe that $X = X^+ \cup X^-$, where
\begin{align}
X^+ & = \{y\in X\mid \text{there exists a path of even length connecting $x$ and $y$}\},\\
X^- & = \{y\in X\mid \text{there exists a path of odd length connecting $x$ and $y$}\}.
\end{align}
Also, $X^+$ is contained in an orbit $O^+$ of $\mathrm{Aut}(\Gamma)$, and $X^-$ is contained in an orbit $O^-$ of $\mathrm{Aut}(\Gamma)$.

Now $O^+\cap O^- = \emptyset$ (else $O^+ = O^- = X$ and vertex transitive).
So,
$X = O^+$, and $X^- = O^-$. 

Also $X^+ \cup X^- = X$ is a bipartition by construction.

$(ii)$ Fix $x, y, x', y'$ with $\partial(x,y) = \partial(x',y')$. 

By vertex transitivity, there exists an element 
$$g_1\in G \text{ such that } g_1x = x'.$$
Observe that 
$$\partial(x', y') = \partial(x,y) = \partial(g_1x, g_1y) = \partial(x', g_1y).$$
Hence, there exisits an element 
$$g_2\in G \text{ such that } g_1x' = x', g_2y' = g_1y, g_2g_1y = y'$$
by (G($x'$)) property.

Set $g = g_2g_1$. Then 
$$gx = x', gy = y'$$
by construction.
:::

The following graphs $\Gamma = (X, E)$ are vertex transitive, and satisfy the property (G($x$)) for all $x\in X$.
$$J(D, N), \quad H(D, r), \quad J_q(D,N),$$
where 

| $H(D,r)$: 
\begin{align}
X & = \{a_1\cdots a_D\mid a_i\in F, 1\leq i\leq D\}\\
& \quad F: \text{ any set of cardinality $r$}\\
E & = \{xy\mid y, x\in X, \; \text{$x$ and $y$ differ in exactly one coordiate}\}.
\end{align}

| $J_q(D, N)$:
\begin{align}
X & = \text{the set of all $D$-dimensional subspaces of $N$-dimensional vector space over $GF(q)$.}\\
& \quad F: \text{ any set of cardinality $r$}\\
E & = \{xy\mid y, x\in X, \; \dim (x\cap y) = D-1\}.
\end{align}

The following graph is distance-transitive but does not satisify (G($x$)) for any $x\in G$.

| $H_q(D,N)$: 
\begin{align}
X & = \text{the set of all $D\times N$ matrices with entries in $GF(q)$}.\\
E & = \{xy\mid y, x\in X, \; \mathrm{rank}(x-y) = 1\}.
\end{align}

:::{.hs}
**HS MEMO**

| $H(D,r)$: $G = S_r \mathrm{wr} S_D$, $G_x = S_{r-1} \mathrm{wr} S_D$, 
For $x, y\in X$ with $\partial(x, y) = \partial(x,z) = i$,
\begin{align}
Y = \{j\in \Omega \mid x_j\neq y_j\} & \leftrightarrow Z = \{j\in \Omega \mid x_j\neq z_j\}\\
(y_{j_1}, \ldots, y_{j_i}) & \leftrightarrow (z_{\ell_1}, \ldots, z_{\ell_i})
\end{align}

| $J(D, N)$: $G = S_N$, $G_x = S_D \times S_{N-D}$.
\begin{align}
X\cap Y & \leftrightarrow X \cap Z\\
(\Omega \setminus X)\cap Y & \leftrightarrow (\Omega \setminus X)\cap Z.
\end{align}

| $J_q(D,N)$: 
$$X\cap Y  \leftrightarrow X \cap Z.$$
:::

The theory of a single thin irreducible $T$-module.

Let $\Gamma = (X, E)$ be any graph.
\begin{align}
M & = \text{Bose-Mesner algebra over $K/\mathbb{C}$ generated by the adjacency matrix $A$.}\\
& = \mathrm{Span}(E_0, \ldots, E_R).
\end{align}

$M$ acts on the standard module $V = \mathbb{C}^{|X|}$. 

Fix $x\in X$, let 
$D \equiv D(x)$ be the $x$-diameter, and $k = k(x)$ be the valency of $x$.

