# Thin $T$-Module, I {#lec9}
**Monday, February 8, 1993**

Let $\Gamma = (X, E)$ be any graph.

$M$:  Bose-Mesner algebra over $K/\mathbb{C}$ generated by the adjacency matrix $A$.

$\quad M = \mathrm{Span}(E_0, \ldots, E_R)$.

$M$ acts on the standard module $V = \mathbb{C}^{|X|}$. 

Fix $x\in X$, let 
$D \equiv D(x)$ be the $x$-diameter, and $k = k(x)$ be the valency of $x$.

:::{.definition}
Pick $x\in X$ and write $E_i^* \equiv E_i^*(x)$ and $T \equiv T(x)$.

Let $W$ be an irreducible thin $T$-module with endpoint $r$, diameter $d$.

Let $a_i = a_i(W)\in \mathbb{C}$ satisfying
$$E_{r+i}^*A{E^*_{r+i}|}_{E_{r+i}^*W} = a_i1|_{E_{r+i}^*} \quad (0\leq i\leq d).$$
Let $x_i = x_i(W)\in \mathbb{C}$ satisfying
$$E_{r+i-1}^*A{E^*_{r+i}AE^*_{r+i-1}|}_{E_{r+i-1}^*W} = x_i1|_{E_{r+i-1}^*} \quad (0\leq i\leq d).$$
:::

:::{.lemma #thin-module-structure}
With above notation, the following hold.

| $(i)$ $a_i\in \mathbb{R} \quad (0\leq i\leq d)$.

| $(ii)$ $x_i\in \mathbb{R}^{>0} \quad (0\leq i\leq d)$.

| $(iii)$ Pick $0\neq w_0\in E^*_rW$. Set $w_i = E^*_{r+i}A^iw_0$ for all $i$. Then  

$\quad (iiia)$ $w_0, w_1, \ldots, w_d$ is a basis for $W$, $w_{-1} = w_{d+1} = 0$.  
$\quad (iiib)$ $Aw_i = w_{i+1} + a_iw_{i} + x_iw_{i-1} \quad (0\leq i\leq d)$.

| $(iv)$ Define $p_0, p_1, \ldots, p_{d+1}\in \mathbb{R}[\lambda]$ by
$$p_0 = 1, \quad \lambda p_i = p_{i+1} + a_i p_i + x_i p_{i-1} \quad (0\leq i\leq d),\quad p_{-1} = 0.$$

 $\quad (iva)$ $p_i(A)w_0 = w_i, \quad (0\leq i\leq d+1)$.   
 $\quad (ivb)$ $p_{d+1}$ is the minimal polynomial of $A|_W$.
:::

:::{.proof}
$(i)$ $a_i$ is an eigenvalue of a real symmetric matrix $E_{r+i}^*AE^*_{r+i}$.

$(ii)$ $x_i$ is an eigenvalue of a real symmetrix matrix $B^\top B$, where 
$$B = E^*_{r+i}AE^*_{r+i-1}.$$
Hence, $x_i\in \mathbb{R}$.

Since $B^\top B$ is positive semidefinite, 
$$x_i \geq 0.$$
_Pf._ If $B^\top Bv = \sigma v$ for some $\sigma \in \mathbb{R}$, $v\in \mathbb{R}^m \setminus \{0\}$, then 
$$0\leq \|Bv\|^2 = v^\top B^\top Bv = \sigma v^\top v = \sigma \|v\|^2, \quad \|v\|^2 >0.$$
Hence, $\sigma \geq 0$.

Moreover, $x_i\neq 0$ by Lemma \@ref(lem:irreducible) $(iv)$.

$(iiia)$ Observe
$$w_i = E^*_{r+i}AE^*_{r+i-1}w_{i-1} \quad (1\leq i \leq d).$$
So $w_i \neq 0 \quad (0\leq i \leq d)$ by Lemma \@ref(lem:irreducible) $(iv)$.

Hence,
$$W = \mathrm{Span}(w_0, \ldots, w_d)$$
by Lemma \@ref(lem:irreducible). $(iii)$.

$(iiib)$ We have that
\begin{align}
Aw_i & = E^*_{r+i+1}Aw_i + E_{r+i}^*Aw_i + E^*_{r+i-1}Aw_i\\
& = w_{i+1} + E^*_{r+i}AE^*_{r+i}w_i + E^*_{r+i-1}AE^*_{r+i}AE^*_{r+i-1}w_{i-1}\\
& = w_{i+1} + a_iw_{i} + x_iw_{i-1}.
\end{align}

$(iva)$ Clear for $i=0$. Assume it is valid for $0, \ldots, i$.
$$p_{i+1}(A)w_0 = (A-a_iI)w_i - x_iw_{i-1} = w_{i+1}.$$

$(ivb)$ By definition,
$$p_{d+1}(A)w_0 = 0.$$
Moreover, $p_{d+1}(A)W = 0$ because of the following. 

For every $w\in W$, write
\begin{align}
w & = \sum_{i=0}^d \alpha_i w_i \\
& = \sum_{i=0}^d \alpha_i p_i(A)w_0 && \text{for some }\alpha_i\in\mathbb{C}\\
& = p(A)w_0 && \text{for some }p\in \mathbb{C}[\lambda].
\end{align}
Hence, 
\begin{align}
p_{d+1}(A)w & = p_{d+1}(A)p(A)w_0\\
& = p(A)p_{d+1}(A)w_0\\
& = 0.
\end{align}

Note that $p_{d+1}$ is the minimal polynomial.

_Pf._ 
Suppose $q(A)W = 0$ for some $0\neq q\in \mathbb{C}[\lambda]$ with $\deg q < \deg p_{d+1} = d+1$.
Then, 
$$q = \sum_{i=0}^d\beta_ip_i \quad \text{for some }\beta_i\in \mathbb{C}.$$
We have, 
$$0  = q(A)w_0  = \sum_{i=0}^d \beta_iw_i.$$
Hence $\beta_0 = \cdots = \beta_d = 0$ by $(iiia)$. Thus $q = 0$, and a contradiction.
:::

:::{.corollary #thin-is-dualthin}
Let $\Gamma$, $W$, $r$, $d$ be as above. Then

| $(i)$ $W$ is dual thin, that is, 
$$\dim E_iW \leq 1 \quad (1\leq i \leq d).$$

| $(ii)$ $d = |\{i \mid E_iW \neq 0\}| - 1.$
:::


:::{.proof}
$(i)$ Set as in Lemma \@ref(lem:thin-module-structure),
$$w_i = p_i(A)w_0\in E^*_{r+i}W.$$
Then $w_0, w_1, \ldots, w_d$ is a basis for $W$. We have
$$W = Mw_0.$$
So, 
$$E_iW = E_iMw_0 = \mathrm{Span}(E_iw_0).$$
Thus,
$$\dim E_iW = \begin{cases}1 & \text{if } E_iw_0\neq 0,\\ 0 & \text{if }E_iw_0 = 0.\end{cases}$$
In particular, 
$$\dim E^*_iW \leq 1.$$

$(ii)$ Immediate as 
$$\dim W = d+1.$$
This proves the lemma.
:::

:::{.lemma #measure-wi}
Given an irreducible $T(x)$-module $W$ with endpoint $r = r(W)$, diameter $d = d(W)$. Write
$$x_i = x_i(W) \; (0\leq i\leq d), \quad w_i = p_i(A)w_0\in E^*_{r+i}W \; (0\leq i\leq d), \quad 0\neq w_0 \in E^*_rW.$$
Then, 
$$\frac{\|w_i\|^2}{\|w_0\|^2} = x_1x_2\cdots x_i \quad (1\leq i\leq d).$$
:::

:::{.proof}
It suffices to show that
$$\|w_i\|^2 = x_i\|w_i\|^2 \quad (1\leq i\leq d).$$
Recall by Lemma \@ref(lem:thin-module-structure) $(iiib)$ that
$$Aw_j = w_{j+1} + a_jw_j + x_jw_{j-1} \quad (0\leq j\leq d), \quad w_{-1} = w_{d+1} = 0.$$
Now observe,
\begin{align}
\langle w_{i-1}, Aw_i\rangle & = \langle w_{i-1}, w_{i+1}+ a_iw_i + x_iw_{i-1}\rangle\\
& = \overline{x_i}\|w_{i-1}\|^2\\
& = x_i\|w_{i-1}\|^2.
\end{align}
by Lemma \@ref(lem:thin-module-structure) $(ii)$.
Also,
\begin{align}
\langle w_{i-1}, Aw_i\rangle & = \langle Aw_{i-1}, w_i\rangle \quad (\text{since}\; \bar{A}^\top = A)\\
& = \langle w_i + a_{i-1}w_{i-1} + x_{i-1}w_{i-2}, w_i\rangle\\
& = \|w_i\|^2.
\end{align}
This proves the lemma.
:::

:::{.definition #measure}
Let $W$ be an irreducible thin $T(x)$ module with endpoint $r$, $E^*_i \equiv E_i^*(x)$. 

The measure \index{measure} $m = m_W$ is the function
$$m: \mathbb{R} \to \mathbb{R}$$
such that
$$
m(\theta) = \begin{cases}\frac{\|E_iw\|^2}{\|w\|^2} & \text{where } 0\neq w \in E^*_rW\\
& \text{ if $\theta = \theta_i$ is an eigenvalue for $\Gamma$,}\\
0 & \text{if $\theta$ is not an eigenvalue for $\Gamma$.}
\end{cases}$$
:::
