# Parameters of Thin Modules, I {#lec14}
**Friday, February 19, 1993** 

Summary.

:::{.definition}
Assume $\Gamma = (X, E)$ is distance-regular with respect to every vertex $x\in X$.

Notation: Let $x\in X$. The data of the trivial $T(x)$-module.

$$\begin{array}{|c|c|c|}
\hline
& \text{Case DR}  & \text{Case DBR} \\
\hline
\text{valency} k_x & k & \begin{cases} k^+ & \text{ if } x\in X^+\\
k^- & \text{ if } x\in X^-\end{cases}\\
x\text{-diameter } D_x & D & \begin{cases} D^+ & \text{ if } x\in X^+\\
D^- & \text{ if } x\in X^-\end{cases}\\
\text{measure $m_x$} & m & \begin{cases} m^+ & \text{ if } x\in X^+\\
m^- & \text{ if } x\in X^-\end{cases}\\
\text{int. number }c_i(x) & c_i & \begin{cases} c_i^+ & \text{ if } x\in X^+\\
c_i^- & \text{ if } x\in X^-\end{cases}\\ 
\text{int. number }b_i(x) & b_i & \begin{cases} b_i^+ & \text{ if } x\in X^+\\
b_i^- & \text{ if } x\in X^-\end{cases}\\ 
\text{int. number }a_i(x) & a_i & \begin{cases} a_i^+ & \text{ if } x\in X^+\\
a_i^- & \text{ if } x\in X^-\end{cases}\\ 
\hline
\end{array}$$

Call $m$, $m^{\pm 1}$ the measure of $\Gamma$.
:::

Assume $\Gamma = (X, E)$ is distance-regular.

To what extent do $a_i$'s, $b_i$'s and $c_i$'s determine the structure of irreducible $T(x)$-modules? In general the following hold.

:::{.lemma #basic-data}
Assume $\Gamma = (X, E)$ is distance-regular. Pick $x\in X$. Let $X$ be a thin irreducible $T(x)$-module with endpoint $r$, diameter $d$ and measure $m_W$. 

| $(i)$ There is a unique polynomial $f_W \in \mathbb{C}[\lambda]$ with the following properties.  

| $\quad (ia)$ $\deg f_W \leq D$ (diameter of $\Gamma$).

| $\quad (ib)$ $m_W(\theta) = m(\theta)f_W(\theta)$ for every $\theta\in \mathbb{R}$, where $m$ is the measure of $\Gamma$.

Moreover, $f_W\in \mathbb{R}[\lambda]$, and 

| $(ii)$ $\deg f_W \leq 2r$.
| $(iii)$ For all eigenvalues $\theta_i$ of $\Gamma$, $\lambda - \theta_i$ is a factor of $f_W$ whenever, $E_iW = 0$. 
In particular, $2r-D+d\geq 0$.
:::

:::{.proof}
Let $\theta_0, \ldots, \theta_D$ denote distinct eigenvalues of $\Gamma$. Then $m(\theta_i) \neq 0$ $(0\leq i\leq D)$ by Proposition \@ref(prop:dim-diamter).

There exists a unique $f_W\in \mathbb{C}[\lambda]$ with $\deg f_W\leq D$ such that
$$f_W(\theta_i) = \frac{m_W(\theta_i)}{m(\theta_i)} \quad (0\leq i\leq D)$$
by polynomial interpolation.

$f_W\in \mathbb{R}[\lambda]$ since 
$$\theta_0, \ldots, \theta_D\in \mathbb{R} \quad \text{and}\quad f_W(\theta_0), \ldots, f_W(\theta_D) \in \mathbb{R}.$$

$(ii)$ Without loss of generality, we may assume $r < D/2$, else trivial.

Pick $0\neq w \in E^*_r(x)W$.
$$w = \sum_{y\in W, \partial(x,y) = r}\alpha_y\hat{y} \quad \text{ some } \; \alpha_y\in \mathbb{C}.$$
Pick $y\in X$ such that $\alpha_y\neq 0$.

Set $W'$ be the trivial $T(y)$-module. ($\langle w, \hat{y}\rangle \neq 0, \text{ as } W\not\bot W'$.)
$$r' = 0, \quad m' = m, \quad \Delta = r.$$

Apply Theorem \@ref(thm:two-thin-modules), we have
\begin{align}
\deg p & \leq \Delta - r' + r = 2r, \quad p\neq 0\\
\deg p' & \leq \Delta - r + r' = 0 , \quad p'\neq 0.
\end{align}
$$m_W(\theta)\overline{p'(\theta)} = m(\theta)p(\theta) \quad (\text{ for all } \theta \in \mathbb{R}).$$
So, 
$$\deg p/\bar{p}' \leq 2r,$$
and $p/\bar{p}'$ satisfies the conditions of $f_W$.
$$\left(\frac{p(\theta)}{\bar{p}'(\theta)} = \frac{m_W(\theta)}{m(\theta)}\right)$$

$(iii)$ 
$$E_iW = 0 \rightarrow m_W(\theta_i) = 0 \rightarrow f_W(\theta_i) = 0.$$
that is, $E_iW = 0$. Hence $\theta_i$ is a root of $f_W(\lambda) = 0$.
So,
$$2r \geq \deg f_W \geq |\{\theta_i\mid E_iW = 0\}| = D-d.$$
Hence, 
$$2r-D + d \geq 0.$$
This proves the assertions.
:::


:::{.lemma #thin-endpoint1}
Let $\Gamma = (X, E)$ be any distance-regular graph with valency $k$, diameter $D$ $(d\geq 2)$, measure $m$, and eigenvalues
$$k = \theta_0 > \theta_1 > \cdots > \theta_D.$$
Pick $x\in X$. Let 
$W$ be a thin irreducible $T(x)$-module with endpoint $r = 1$, diameter $D$ and measure $m_W = mf_W$.
Then one fo the following cases $(i)-(iv)$ occurs.

$$\begin{array}{|c|c|c|c|}
\hline
\text{Case} & d  & f_W(\lambda) & a_0(W) \\
\hline
(i) & D-2 & \frac{(\lambda - k)(\lambda - \theta_1)}{k(\theta_1 + 1)} & -\frac{b_1}{\theta_1 + 1} -1\\
(ii) & D-2 & \frac{(\lambda - k)(\lambda - \theta_D)}{k(\theta_D + 1)} & -\frac{b_1}{\theta_1 + 1} -1\\
(iii) & D-1 & \frac{k - \lambda}{k} & -1\\
(iv) & D-1 & \frac{(\lambda - k)(\lambda - \beta)}{k(\beta + 1)} & -\frac{b_1}{\beta + 1} -1\\ 
\hline
\end{array}$$
for some $\beta\in \mathbb{R}$ with $\beta\in (-\infty, \theta_D) \cup (\theta_1, \infty)$.
Moreover, the isomorphism class of $W$ is determined by $a_0(W)$.
:::

**Note.** By $(iii)$, the possible "shapes" of a thin irreducible $T(x)$-modules are:
\begin{align}
r = 0 & \quad d = D\\
r = 1 & \quad d = D-1\\
r = 1 & \quad d = D-2
\end{align}
