# Association Schemes {#lec17}
**Monday, March 1, 1993** 

**Review**

Let $\Gamma = (X, E)$ be a distance-regular graph of diameter $D\geq 2$. Pick a vertex $x\in X$. 

Let $W$ be a thin irreducible $T(x)$-module with endpoint $r = 1$, diameter $d = D-1$ or $D-2$, and $r_0 = a_(W) + 1$.

Show
$$\gamma_i = \frac{c_2c_2\cdots c_{i+1}b_2b_3\cdots b_{i+1}\gamma_0}{x_1(W)\cdots x_i(W)},$$
$a_i(W)$ and $x_i(W)$ are all algebraic integers in $\mathbb{Q}[\gamma_0]$, where
\begin{align}
x_i(W) & = c_ib_i + \gamma_{i-1}(a_i + c_i - c_{i+1}-a_{i-1}(W)) && (1\leq i\leq d)\\
a_i(W) & = \gamma_i - \gamma_{i-1} + a_i + c_i - c_{i+1} && (1\leq i\leq d)
\end{align}

Certainly, $x_i(W)$, $\gamma_i$, and $a_i(W)$ are in $\mathbb{Q}[\gamma_0]$ by the above lines and so on.
$$\gamma_0 \to a_0(W) \to x_1(W) \to \gamma_1 \to a_1(W)\to x_1(W) \to \cdots .$$
Recall some $B\in \mathrm{Mat}_n(\mathbb{C})$ is integral whenever
$$B\in \mathrm{Mat}_n(\mathbb{Z}).$$
In this case, the characteristic polynomial
$$\det(\lambda I - B) = \lambda^n + \alpha_{n-1}\lambda^{n-1} + \cdots + \alpha_0, \quad \text{some }\; \alpha_0, \ldots, \alpha_{n-1}\in \mathbb{Z}.$$
Hence, eigenvalues of $B$ are algebraic integers.
But $a_i(W)$ is an eigenvalue of an integral matrices, 
$$B = E^*_{i+1}(x)AE^*_{i+1}(x).$$
Hence, $a_i(W)$ is an algebraic integer.

Also, $x_i(W)$ is an eigenvalue of an integral matrix
$$B = E^*_i(x)AE^*_{i+1}(x)AE^*_i(x).$$
So $x_i(W)$ is an algebraic integer.
$$\gamma_i - \gamma_{i-1} = a_i(W) - a_i - c_i + c_{i+1}$$
is an algebraic integer.

Since $\gamma_0 = a_0(W) + 1$ is an algebraic integer, we find $\gamma$ is an algebraic integer for all $i$.

:::{.definition #association-scheme}
A (commutative) association scheme\index{association scheme} is a configuration $Y = (X, \{R_i\}_{0\leq i\leq D})$, where $X$ is a finite nonempty set (of vertices),
$R_0, R_1, \ldots, R_D$ are nonempty subsets of $X\times X$ such that

| $(i)$ $R_0 = \{(x,x)\mid x\in X\}$,

| $(ii)$ $R_0 \cup \cdots \cup R_D = X\times X \quad (\text{disjoint union})$,

| $(iii)$ for every $i$, $R_i^\top = \{(y,x)\mid xy\in R\} = R_{i'}$ some $i'\in \{0,1,\ldots, D\}$,

| $(iv)$ for every $h, i, j$ ($0\leq h, i, j\leq D$), and every $x,y\in X$ such that $(x,y)\in R_h$, 
$$p^h_{ij} = |\{z\in X\mid (x,z)\in R_i, \; (z,y)\in R_j\}|$$
depends only on $h, i, j$ and not on $x,y$; and

| $(v)$ $p^h_{ij} = p^h_{ji}$ for all $h,i, j$.

If $i' = i$ for all $i$, we say $Y$ is symmetric\index{symmetrix}.
We call $D$ the class of scheme and $R_i$, the $i$th relation of $Y$. We say vertices $x,y\in X$ are $i$-related, or 'at distance $i$', whenever $(x,y)\in R_i$.

We always assume that a 'scheme' is a commutative association scheme.
:::

Let $Y = (X, \{R_i\}_{0\leq i\leq D})$ be an association scheme.

:::{.definition #incidencemat-of-as}
The $i$-the association matrix\index{association matrix} $A_i\in \mathbb{Mat}_X(\mathbb{C})$
\begin{align}
(A_i)_{xy} & = \begin{cases} 1 & \text{if}\; (x,y)\in R_i\\
0 & \text{if}\; (x,y)\not\in R_i,\end{cases} && (x,y\in X, 0\leq i\leq D)
\end{align}
Then,

| $(i')$ $A_0 = I$.

| $(ii')$ $A_0 + A_1 + \cdots + A_D = J$ (= all 1's matrix).

| $(iii')$ $A_i^\top = A_{i'}$ ($0\leq i\leq D$).

| $(iv')$ ${\displaystyle A_iA_j = \sum_{h=0}^D p^h_{ij}A_h\quad }$ $(0\leq i,j\leq D)$.

| $(v')$ $A_iA_j = A_jA_i$.

| $M := \mathrm{Span}_{\mathbb{C}}(A_0, \ldots, A_D)$ (Bose-Mesner algebra of $Y$) is a commutative $\mathbb{C}$-algebra of dimension $D+1$.
::: 

Observe:
$$Y \text{ is symmetric} \leftrightarrow A_i^\top = A_i \text{ for all } i \leftrightarrow M \text{ is symmetric}.$$

:::{.example #dr}
Let $\Gamma = (X, E)$ be distance-regular of diameter $D$. Set
\begin{align}
R_i & = \{(x,y)\mid \partial(x,y) = i\} && (0\leq i\leq D).
\end{align}
Then,
$$Y = (X, \{R_i\}_{0\leq i\leq D})$$
is a symmetric scheme. 
$$i\text{-th association matrix} = i\text{-th distance matrix} \quad \text{for all $i$.}$$
:::


:::{.example #gen-tr}
Suppose a group $G$ acts transitively on a seet $X$. Assume $G$ is generously transitive, i.e., 
$$\text{for all }x,y\in X, \text{ there exists }g\in G \text{ such that }gx = y, gy = x.$$
Then $G$ acts on $X\times X$ by rule;
$$g(x,y) = (gx, gy), \quad \text{for all }\; g\in G, \text{ and for all }x,y\in X.$$
Let $R_0, \ldots, R_D$ denote orbits of $G$ on $X\times X$. 

Observe that $R_i^\top = R_i$ for all $i$ by generously transitivity, and
$$Y = (X, \{R_i\}_{0\leq i\leq D})$$
is a symmetric scheme.
:::


:::{.exercise #gen-tr-case}
In Example Example \@ref(exm:gen-tr), Bose-Mesner algebra
\begin{align}
M & = \{B\in \mathrm{Mat}_X(\mathbb{C}) \mid Bg = gB, \text{ for all }g\in G\}\\
& = \text{the commuting algebra of $G$ on $X$.}
\end{align}
Here, we view each $g\in G$ as a permutation matrix in $\mathrm{Mat}_X(\mathbb{C})$ satisfying
$$g\hat{x} = \widehat{gx}, \quad \text{for all }x\in G.$$
:::

:::{.example #centralizer-alg}
Let $G$ be any finite group. $G$ acts on $X = G$ by conjugation.
$$G\times X \to X, \quad (g,x)\mapsto gxg^{-1}.$$
Let $C_0, C_1, \ldots, C_D$ denote orbits (i.e., conjugacy classes), and let $C_0 = \{1_G\}$.
Claim that $Y = (X, \{R_i\}_{0\leq i\leq D})$ is a commutative scheme (not symmetric in general).

| $(i)$ $R_0 = \{xx\mid x\in X\}$ as $C_0 = \{1_G\}$.

| $(ii)$ $R_0, \ldots, R_D$ is a partition of $X\times X$ since $C_0, \ldots, C_D$ is a partition of $X = G$.

| $(iii)$ $R_i^\top = R_{i'}$, where $C_{i'} = \{g^{-1}\mid g\in C_i\}$.

| $(iv)$ Set $H = G\oplus G$, the direct sum. Then $H$ acts on $X = G$:
$$\text{for all }h = (g,gz), \text{for all }x\in X, \quad h(x) = gx(gx)^{-1} = gxz^{-1}g^{-1}.$$
$$R_i = \{(x,y)\mid x^{-1}y\in C_i\}, \; h_i\in C_i, \; x^{-1}y = gh_ig^{-1}.$$
\begin{align}
(x,y) & = (x, xgh_ig^{-1})\\
& = (xgg^{-1}, xgh_ig^{-1})\\
& = (xg, g)(1,h_i).
\end{align}
So, $R_0, \ldots, R_D$ are the orbits of $H$ on $X\times X$.

| $(v)$ $p^h_{ij} = p^h_{ji}$?


Fix $i,j, h$ and $x, y\in X$ with $(x,y)\in R_h$. Set
\begin{align}
S & = \{z\in X\mid (x,z)\in R_i, \; (z,y)\in R_j\}\\
T & = \{z\in X\mid (x,z)\in R_j, \; (z,y)\in R_i\}.
\end{align}
Show $|S| = |T|$.
$$\text{For all }z\in S, \text{ set } \hat{z} = xz^{-1}y.$$
Observe, $\hat{z}\in T$.
\begin{align}
x^{-1}z\in C_i & x^{-1}\hat{z} = x^{-1}xz^{-1}y\in C_j\\
z^{-1}y\in C_j & \hat{z}^{-1}y = y^{-1}zx^{-1}x^{-1}y = y^{-1}x(x^{-1}z)x^{-1}y \in C_i.
\end{align}
Observe
$$S\to T \quad (z\mapsto z^{-1}) \quad \text{is one-to-one and onto.}$$
:::
