# Vanishing Conditions {#lec20}
**Monday, March 15, 1993** (Monday after Spring break)

:::{.lemma #pij-qij}
Let $Y = (X, \{R_i\}_{0\leq i\leq D})$ be a commutative scheme. 

| $(i)$ $p_0(i) = 1$.

| $(ii)$ $p_i(0) = k_i$, where 
$$k_i = p^0_{ii'} = |\{y\in X\mid (x,y)\in R_i\}|.$$

| $(iii)$ $q_0(i) = 1$.

| $(iv)$ $q_i(0) = m_i$, where
$$m_i = \mathrm{rank} E_i.$$
:::

:::{.proof}
| $(i)$ Since $A_0 = I$ and
\begin{align}
A_0 & = p_0(0)E_0 + p_0(1)E_1 + \cdots + p_0(D)E_D\\
I & = E_0 + E_1 + \cdots + E_D,
\end{align}
$p_0(i) = 1$ for all $i$.

| $(ii)$ Since
$$A_i = p_i(0)E_0 + p_i(1)E_1 + \cdots + p_i(D)E_D,$$
$A_i E_0 = p_i(0)E_0$, and 
$$k_i J = A_i J = p_i(0)J$$
as there are $k_i$ $1$'s in each row of $A_i$, we have $k_i = p_i(0)$. 

| $(iii)$ Since $E_0 = |X|^{-1}J$ and
\begin{align}
E_0 & = |X|^{-1}(q_0(0)A_0 + q_0(1)A_1 + \cdots + q_0(D)A_D)\\
|X|^{-1}J & = |X|^{-1}(A_0 + A_1 + \cdots + A_D),
\end{align}
$q_0(i) = 1$ for all $i$.

| $(iv)$ $E_i = |X|^{-1}(q_i(0)A_0 + q_i(1)A_1 + \cdots + q_i(D)A_D)$, $E_i^2 = E_i$, and $E_i$ is similar to a matrix
$$\begin{pmatrix} I_{m_i} & O \\ O & O\end{pmatrix}.$$
So, 
$$m_i = \mathrm{rank}E_i = \mathrm{trace} E_i = \sum_{x\in X}(E_i)_{xx} = |X||X|^{-1}q_i(0) = q_i(0).$$
Note that as 
$$E_i = \frac{1}{|X|}\sum_{j=0}^D q_i(j)A_j \to (E_i)_{xx} = \frac{1}{|X|}q_i(0)(A_0)_{xx}.$$
Hence, we have all formulas.
:::


:::{.lemma #phijqhij}
With the above notation

| $(i)$ $p^h_{ij} = p^{h'}_{j'i'}$.

| $(ii)$ $k_hp^h_{ij} = k_jp^j_{i'h} = k^i_{hj'}$.

| $(iii)$ $q^h_{ij} = q^{\hat{h}}_{\hat{j}\hat{i}}$.

| $(iv)$ $m_hq^h_{ij} = m_jq^j_{\hat{i}h} = m_iq^i_{h\hat{j}}.$
:::

:::{.proof}
| $(i)$ We have
\begin{align}
\sum_{h = 0}^D p^h_{ij} A_{h'} & \left(\sum_{h=0}^D p^h_{ij}A_h\right)^\top \\
 & = (A_iA_j)^\top  \\
& = A_j^\top A_i^\top\\
& = A_{j'}A_{i'} \\
& = \sum_{h=0}^D p^{h'}_{j'i'}A_h'.
\end{align}

| $(ii)$ Count the following number,
\begin{align} 
& |\{xyz\in X^3 \mid (x,y)\in R_h, (x,z)\in R_i, (z,y)\in R_j\}| \\
& \quad =  |X|k_hp^h_{ij} = |X|k_jp^j_{i'h} = |X|k^i_{hj'}.
\end{align}

| $(iii)$ 
\begin{align}
\frac{1}{|X|}\sum_{h = 0}^D q^h_{ij} E_{\hat{h}} & = \left(\frac{1}{|X|}\sum_{h=0}^D q^h_{ij}E_h\right)^\top \\
 & = (E_i\circ E_j)^\top  \\
& = E_j^\top \circ E_i^\top\\
& = E_{\hat{j}}E_{\hat{i}} \\
& = \frac{1}{|X|}\sum_{h=0}^D q^{\hat{h}}_{\hat{j}\hat{i}}E_{\hat{h}}.
\end{align}

| $(iv)$ Let $\tau(B)$ denote the sum of the entries in the matrix $B$.

Observe: $\tau(B\circ C) = \mathrm{trace}(BC^\top)$.

Observe
$$\tau(E_i\circ E_j \circ E_{\hat{k}}) = \tau((E_i\circ E_j\circ E_{\hat{k}})^\top) = \tau(E_{\hat{i}}\circ E_k \circ E_{\hat{j}}) = \tau(E_k\circ E_{\hat{j}}\circ E_{\hat{i}}).$$
Compute each one.
\begin{align}
\tau(E_i\circ E_j \circ E_{\hat{k}}) & = \mathrm{trace}((E_i\circ E_j)E_k) = \mathrm{trace}\left(\left(\frac{1}{|X|}\sum_{h} q^h_{ij}E_h\right)E_k\right)\\
& = \mathrm{trace}\left(\frac{1}{|X|} q^k_{ij}E_k\right) = \frac{1}{|X|}m_kq^k_{ij},\\
\tau(E_{\hat{i}}\circ E_k \circ E_{\hat{j}}) & = \mathrm{trace}((E_{\hat{i}}\circ E_k)E_{\hat{j}}) = \mathrm{trace}\left(\left(\frac{1}{|X|}\sum_{h} q^h_{\hat{i}k}E_h\right)E_{\hat{j}}\right)\\
& = \mathrm{trace}\left(\frac{1}{|X|} q^j_{\hat{i}k}E_k\right) = \frac{1}{|X|}m_jq^j_{\hat{i}k},\\
\tau(E_k\circ E_{\hat{j}}\circ E_{\hat{i}}) & = \mathrm{trace}((E_k\circ E_{\hat{j}})E_i) = \mathrm{trace}\left(\left(\frac{1}{|X|}\sum_{h} q^h_{k\hat{j}}E_h\right)E_i\right)\\
& = \mathrm{trace}\left(\frac{1}{|X|} q^i_{k\hat{j}}E_i\right) = \frac{1}{|X|}m_iq^i_{k\hat{j}}.
\end{align}
Hence, we have $(iv)$.
:::

:::{.lemma #vanishing-condition}
Let $Y = (X, \{R_i\}_{0\leq i\leq D})$ be a commutative scheme. Fix a vertex $x\in X$, and set $E^*\equiv E^*_i(x)$ and $A^*_i \equiv A^*(x)$.
Then the following hold.

| $(i)$ $E^*_iA_jE^*_k = O$ if and only if $p^k_{ij} = 0$ for $0\leq i,j,k\leq D$.

| $(ii)$ $E_iA^*_jE_k = O$ if and only if $q^k_{ij} = 0$ for $0\leq i,j,k\leq D$.
:::

:::{.proof}
| $(i)$ Partition rows and columns by $R_0(x), R_1(x), \ldots, R_D(x)$. Then,
$$E^*_i(x)A_j E^*_h(x)$$
is the $(i,h)$ block of $A_j$. 

Hence this submatrix is zero if and only if there exists no $y,z\in X$ such that $(x,y)\in R_i$, $(x,z)\in R_h$ and $(y,z)\in R_j$. This is exactly when $p^h_{ij} = 0$.


| $(ii)$ The sum of the squares of norms of entries in $E_iA^*_jE_k$
\begin{align}
& = \tau((E_iA^*_jE_k)\circ (\overline{E_jA^*_jE_k}))\\
& = \mathrm{trace}(E_iA^*_jE_k(\overline{E_jA^*_jE_k})^\top)\\
& = \mathrm{trace}(E_iA^*_jE_kA^*_{\hat{j}}E_i)\\
& = \mathrm{trace}(E_iA^*_jE_kA^*_{\hat{j}}) && \text{as $\mathrm{trace}(XY) = \mathrm{trace}(YX)$}\\
& = \sum_{y\in X}(E_iA^*_jE_kA^*_{\hat{j}})_{yy}\\
& = \sum_{y\in X}\left(\sum_{z\in X} (E_i)_{yz}(A^*_j)_{zz}(E_k)_{zy}(A^*_{\hat{j}})_{yy}\right)\\
& = \sum_{y\in X}\left(\sum_{z\in X} (E_{\hat{i}})_{zy}(|X|(E_j)_{xz})(E_k)_{zy}(|X|(E_j)_{yx})\right)\\
& = |X|^2(E_j(E_{\hat{i}}\circ E_k))E_j)_{xx}\\
& = |X|q^j_{\hat{i}k}(E_j)_{xx}\\
& = q^j_{\hat{i}k}m_j \\
& = m_kq^k_{ij}.
\end{align}
Note that since $|X|E_j = q_j(0)A_0 + q_j(1)A_1 + \cdots q_j(D)A_D$, 
$$(E_j)_{xx} = \frac{1}{|X|}q_j(0) = \frac{m_j}{|X|}.$$
Thus, we have $(ii)$.
:::

:::{.corollary #qhij name="Krein Condition"}
For any commutative scheme $Y = (X, \{R_i\}_{0\leq i\leq D})$, $q^h_{ij}$ is a non-negative real number for $0\leq h, i, j\leq D$.
:::

:::{.proof}
Since $q^h_{ij}m_h$ is a non-negative real by the proof of Lemma \@ref(lem:vanishing-condition) $(ii)$.

Note that $m_h$ is a positive integer.
:::


An interpretation of the Krein parameters.

Let $Y = (X, \{R_i\}_{0\leq i\leq D})$ be a commutative scheme with standard module $V$.

Pick a vector $v\in V$ with 
$$v = \sum_{x\in X}\alpha_x \hat{x}.$$
View $v$ as a function
$$v: X\longrightarrow \mathbb{C} \quad (x\mapsto \alpha_x).$$
View $V$ as the set of all functions $V \longrightarrow \mathbb{C}$. Then the vector space $V$ together with product of functions is a $\mathbb{C}$-algebra.

For 
$$v = \sum_{x\in X}\alpha_x \hat{x}, \quad w = \sum_{x\in X}\beta_x \hat{x} \in V,$$
write
$$v\circ w = \sum_{x\in X}\alpha_x\beta_x \hat{x}$$
to represent the product of $v$ and $w$ viewed as functions.

:::{.lemma #vector-function-product}
With the above notation,

| $(i)$ $A^*_j(x)v = |X|(E_{\hat{j}}\hat{x}\circ v)$ for all $v\in V$ and for all $x\in X$.

| $(ii)$ $E_iV\circ E_jV \subseteq \sum_{h: q^h_{ij}\neq 0} E_hV$ for all $0\leq i, j\leq D$.

| $(iii)$ $E_h(E_i\circ E_jV) = E_hV$ if $q^h_{ij}\neq 0$ for all $0\leq h, i, j\leq D$.
:::
