# Representation of a Scheme {#lec23}
**Monday, March 22, 1993** 

:::{.theorem #q-polynomial-space}
Let $Y = (X, \{R_i\}_{0\leq i\leq D})$ be a symmetric scheme. (View the standard module $V$ as an algebra of functions from $X$ to $\mathbb{C}$.) Then the following are equivalent.

| $(i)$ $Y$ is $Q$-polynomial with respect to ordering $E_0, E_1, \ldots, E_D$ of primitive idempotents.

| $(ii)$ For all $i$ $\:(0\leq i\leq D)$,
$$E_0V + E_1V + (E_1V)^2 + \cdots + (E_1V)^i = E_0V + E_1V + \cdots + E_iV.$$
:::

:::{.proof}
| By Lemma \@ref(lem:vector-function-product) $(ii)$, $(iii)$.
$$E_h(E_iV\circ E_jV) = 0 \text{ if and only if } q^h_{ij} = 0 \quad (0\leq i,j,h\leq D).$$

| $(i)\to(ii)$ By our assumption,
$$q^h_{1j} = 0 \text{ if } |h-j|>1, \text{ and } q^{j+1}_{1j}\neq 0.$$
So,
\begin{equation}
E_1V\circ E_jV \subseteq E_{j-1}V + E_jV + E_{j+1}V \quad (0\leq j\leq D), (\#eq:e1vejv)
\end{equation}
\begin{equation}
E_{j+1}(E_1V\circ E_jV) = E_{j+1}V \quad (0\leq j\leq D-1), (\#eq:ej1e1vejv)
\end{equation}
by Lemma \@ref(lem:vector-function-product).

Also $E_0V \subseteq \mathrm{Span}(\delta)$, where $\delta$ is all 1's vector, i.e., $1$ as a function $X\to \mathbb{C}$.
So,
\begin{equation}
E_0\circ E_jV = E_jV \quad (0\leq j\leq D). (\#eq:e0vejv)
\end{equation}
Show $(ii)$ by induction on $i$.

The cases $i=0, 1$ are trivial.

$i>1$: $\subseteq$.
\begin{align}
& E_0V + E_1V + (E_1V)^2 + \cdots + (E_1V)^i\\
& \quad = E_0V + E_1V\circ (E_0V + E_1V + \cdots + (E_1V)^{i-1})\\
& \quad = E_0V + E_1V\circ (E_0V + E_1V + \cdots + E_{i-1}V)\\
& \quad \subseteq E_0V  + E_1V + \cdots + E_{i}V
\end{align}
by \@ref(eq:e1vejv).

$\supseteq$.

Claim. $E_i\subseteq E_1V\circ E_{i-1}V + E_{i-1}V + E_{i-2}V \quad (2\leq i\leq D)$.

_Proof of Claim._ By \@ref(eq:ej1e1vejv),
$$E_i(E_1V \circ E_{i-1}V) = E_iV.$$
For all $v\in E_i V$, there exists $u\in E_1V\circ E_{i-1}V$ such that $E_iu = v$.

On the other hand, by \@ref(eq:e1vejv),
$$E_1V\circ E_{i-1}V \subseteq E_{i-2}V + E_{i-1}V + E_{i-2}V.$$
So, $u = w+v$, where $w\in E_{i-2}V + E_{i-1}V$. We have,
$$w = u-v \in E_1V \circ E_{i-1}V + E_{i-1}V + E_{i-2}V$$
as desired.

:::{.remark}
$$E_iV \circ E_jV = \mathrm{Span}(u\circ v \mid u\in E_iV, v\in E_jV).$$
:::

By claim,
\begin{align}
& E_0V + E_1V + \cdots + E_iV\\
& \quad \subseteq E_0V + E_1V + \cdots + E_iV + E_1V\circ E_{i-1}V\\
& \quad \subseteq E_0V + E_1V + \cdots + (E_{1}V)^{i-1} + E_1V(E_0V + E_1V + \cdots + (E_{1}V)^{i-1})\\
& \quad \subseteq E_0V  + E_1V + \cdots + (E_{1}V)^{i-1} + (E_1V)^{i}.
\end{align}

| $(ii)\to(i)$

Claim 1. Pick $i, j$ $(0\leq i,j\leq D)$ with $j>i+1$. Then $q^j_{1i} = 0$.

_Proof of Claim 1._
\begin{align}
E_j(E_1\circ E_jV) & \subseteq E_j(E_1V\circ(E_0V + E_1V + (E_1V)^2 + \cdots + (E_1V)^i))\\
& \subseteq E_j(E_0V + E_1V + (E_1V)^2 + \cdots + (E_1V)^{i+1})\\
& = E_j(E_0V + E_1V + \cdots + E_{i+1}V)\\
& = 0.
\end{align}
So $q^j_{1i}=0$ by Lemma \@ref(lem:vector-function-product).

Claim 2. $q^{i+1}_{1i} \neq 0$ $(0\leq i < D)$.

_Proof of Claim 2._
\begin{align}
& E_0V + E_1V + \cdots + E_{i+1}V\\
& \quad = E_0V + E_1V + \cdots + (E_1V)^{i+1}\\
& \quad = E_0V + E_1V\circ(E_0V + E_1V + \cdots + (E_{1}V)^{i})\\
& \quad = E_0V + E_1V\circ(E_0V + E_1V + \cdots + E_iV)\\
& \quad = E_0V  + E_1V\circ(E_0V + \cdots + E_iV).
\end{align}
So,
\begin{align}
E_{i+1}V & = E_{i+1}(E_1V\circ (E_0V + \cdots + E_iV))\\
& = E_{i+1}(E_1V \circ E_iV)
\end{align}
by Claim 1 and Lemma \@ref(lem:vector-function-product).

Hence, $q^{i+1}_{1i}\neq 0$ by Lemma \@ref(lem:vector-function-product).
:::


Let $Y = (X, \{R_i\}_{0\leq i\leq D})$ be a commutative scheme with standard module $V$.

:::{.definition #representation-of-y}
A representation of $Y$ is a pair $(\rho, H)$, where $H$ is a non-zero Hermitean space (with inner product $\langle \;, \;\rangle$) and 
$\rho: X\to H$ is a map satisfying the following.

| $\mathrm{R1}$. $H = \mathrm{Span}(\rho(x)\mid x\in X)$.

| $\mathrm{R2}$. $\langle \rho(x), \rho(y)\rangle$ depends only on $i$ for which $(x,y)\in R_i$ $(x,y\in X)$.

| $\mathrm{R3}$. For every $x\in X$ and for all $i$ $(0\leq i\leq D)$,
$$\sum_{y\in X, (y,x)\in R_i}\rho(y)\in \mathrm{Span}(\rho(x)).$$

Above representation is nondegenerate if $\{\rho(x)\mid x\in X\}$ are distinct.
:::

:::{.example #representation-of-hd2}
$Y = H(D,2)$, $X = \{a_1\cdots a_D\mid a_i\in \{1,-1\}, 1\leq i\leq D\}$.
Let $H = \mathbb{C}^D$ and $\langle \;, \;\rangle$ usual Hermitean dot product.

For a vertex $x = a_1\cdots a_D\in X$, define
$$\rho(x) = a_1\cdots a_D\in H.$$
Then, $\mathrm{R1}-\mathrm{R3}$ hold.
:::

:::{.remark}
$\mathrm{R1}, \mathrm{R2}$ are obvious. 
For $\mathrm{R3}$, we may assume that $x = 1\cdots 1$.
Restrict
$$\sum_{y\in X, (y,x)\in R_i}\rho(y)$$
on the first coordinate. Then,
\begin{align}
-1 & \quad \text{appers }\; \binom{D-1}{i-1} \;\text{ times}\\
1 & \quad \text{appers } \;\binom{D-1}{i} \;\text{ times}.
\end{align}
Hence,
$$\sum_{y\in X, (y,x)\in R_i}\rho(y) = \left(\binom{D-1}{i} - \binom{D-1}{i-1}\right)\rho(x).$$
:::

Let $(\rho, H)$ be a representation of arbitrary commutative scheme $Y$. Set
$$E = (\langle \rho(x),\rho(y)\rangle)_{x,y\in X}$$
Gram matrix of the representation.

:::{.definition #equivalence-of-representation}
Representations $(\rho, H)$, $(\rho', H')$ of $Y$ are equivalent, whenever, Gram matrices are related by 
$$E'\in \mathrm{Span} E.$$
We do not distinguish between equivalent representations.
:::

**Note.** 
Suppose $(\rho, H)$ is a representation of a symmetric scheme $Y$. Pick $x,y\in X$ with $(x,y)\in R_j$.

Then $(y,x)\in R_j$. So, by $\mathrm{R2}$,
$$\langle \rho(x), \rho(y)\rangle = \langle \rho(y),\rho(x)\rangle = \overline{\langle \rho(x), \rho(y)\rangle},$$
since $\langle \;, \;\rangle$ is Hermitean.

Hence, the Gram matrix $E$ of $\rho$ is real symmetirc. Without loss of generality, we can view $H$ as a real Euclidean space in this case.


:::{.lemma #rep-of-scheme}
Let $Y = (X, \{R_i\}_{0\leq i\leq D})$ be a commutative scheme and $V$ a standard module.

Let $E_j$ be any primitive idempotent of $Y$.

| $(i)$ $(\rho, H)$ is a representation of $Y$, where $H = E_jV$ (with inner product inherited from $Y$).
$$\rho: X \to H \quad (x\mapsto E_j\hat{x})$$
(i.e., $\rho(x)$ is the $x$-th column of $E_j$.)

| $(ii)$ $\langle \rho(x),\rho(y)\rangle = |X|^{-1}q_j(i)$, if $(x,y)\in R_i$,  $(x,y\in X)$.

| $(iii)$ For $0\leq i\leq D$ and $x,y\in X$,
$$\sum_{y\in X, (y,x)\in R_i}\rho(y) = p_i(j)\rho(x).$$

| $(iv)$ $(\rho,H)$ is nondegenerate if and only if $q_j(i) \neq q_j(0)$ for all $i$, $(0\leq i\leq D)$.

| $(v)$ Every representation of $Y$ is equivalent to a representation of the above type for some $j$ $(0\leq j\leq D)$, and $j$ is unique.
:::

:::{.proof}
| $(i)-(iii)$.

$\mathrm{R1}$: $\mathrm{Span}(\rho X)$ is the column space of $E_j$ which is equal to $H$.

$\mathrm{R2}$: 
\begin{align}
\langle \rho(x),\rho(y)\rangle & = \langle E_j\hat{x}, E_j\hat{y}\rangle \\
& = (\overline{E_j\hat{x}})^\top E_j\hat{y}\\
& = \hat{x}^\top \overline{E_j}^\top E_j\hat{y}\\
& = \hat{x}^\top E_j \hat{y}\\
& (E_j)_{xy}.
\end{align}
Note that $\overline{E_j}^\top = E_j$ by Lemma \@ref(lem:ei).

Recall 
$$E_j = |X|^{-1}(q_j(0)A_0 + \cdots + q_j(D)A_D).$$
So,
$$(E_j)_{xy} = |X|^{-1}q_j(i), \quad \text{ where } \; (x,y)\in R_i.$$

$\mathrm{R2}$: Recall
$$A_i = p_i(0)E_0 + \cdots + p_i(D)E_D.$$
So,
$E_jA_i = p_i(j)E_j$, and 
$$p_i(j)\rho(x) = p_i(j)E_j\hat{x} = E_jA_i\hat{x} = E_j\sum_{y\in X, (y,x)\in R_i}\hat{y} = \sum_{y\in X, (y,x)\in R_i}\rho(y).$$

**Note.**
$$A_i\hat{x} = \sum_{y\in X, (x,y)\in R_{i'}}\hat{y}.$$

_Pf._ 
\begin{align}
\text{$z$ entry of LHS} & = (A_i\hat{x})_z \\
& = \sum_{w\in X}(A_i)_{zw}\hat{x}_w\\
& = (A_i)_{zx}\\
& = \begin{cases}
1 & \text{if $(x,z)\in R_{i'}$}\\
0 & \text{else}.
\end{cases}
\end{align}
\begin{align}
\text{$z$ entry of RHS} & = \sum_{y\in X, (x,y)\in R_{i'}, z = y}1\\
& = \begin{cases}
1 & \text{if $(x,z)\in R_{i'}$}\\
0 & \text{else}.
\end{cases}
\end{align}

| $(iv)$ By $(ii)$,
\begin{align}
\|\rho(x)\|^2 & = \langle \rho(x), \rho(y)\rangle\\
& |X|^{-1}q_j(0)\\
& |X|^{-1}m_j,
\end{align}
as $m_j = \dim E_jV$, and is independent of $x\in X$.

Pick distinct $x,y\in X$ such that $(x,y)\in R_i$ with $i\neq 0$.

Then,
\begin{align}
\rho(x) = \rho(y) & \Leftrightarrow \langle \rho(x),\rho(y)\rangle = \|\rho(x)^2\| = |X|^{-1}q_j(0)\\
& \Leftrightarrow |X|^{-1}q_j(i) = |X|^{-1}q_j(0)\\
& \Leftrightarrow q_j(i) = q_j(0).
\end{align}

Hence, we have $(iv)$. To be continued.
:::
