# Balanced Conditions, I {#lec24}
**Wednesday, March 23, 1993**

No Class on Friday (another conference).

:::{.proof name="Proof of Lemma \@ref(lem:rep-of-scheme) continued"}
Let $E_j$ be a primitive idempotent, $H = E_jV$ and 
$$\rho: X\to H \quad (x\mapsto E_j\hat{x}).$$

| $(v)$ Every representation $(\rho, H)$ of $Y$ is equivalent to a representation of above type, for some $j$ $(0\leq j\leq D)$ and $j$ is unique.

Let $E:=(\langle \rho(x), \rho(y))_{x,y\in X}$.

By $\mathrm{R2}$,
$$E = \sum_{i = 0}^D \sigma_i A_i, \quad \text{some}\; \sigma_0, \sigma_1, \ldots, \sigma_D\in \mathbb{C}.$$
Hence, $E$ belongs to the Bose-Mesner algebra $M of $Y$.

We want to show that $E$ is a scalar multiple of a primitive idempotent.

Fix $x\in X$ and fix $i$ $(0\leq i\leq D)$.

By $\mathrm{R3}$, 
\begin{equation}
\sum_{y\in X, (y,x)\in R_i}\rho(y) = \alpha \rho(x), \quad \text{some }\; \alpha\in \mathbb{C}. (\#eq:sumrhoy)
\end{equation}
So,
$$k_i\overline{\sigma_i} = \left\langle \sum_{y\in X, (y,x)\in R_i}\rho(y),\rho(x)\right\rangle = \bar{\alpha}\langle \rho(x), \rho(x)\rangle = \bar{\alpha}\sigma_0.$$
Hence, $\alpha$ is independent of $x$. In maatrix form \@ref(eq:sumrhoy) becomes 
$$EA_i\hat{x} = \alpha E\hat{x}.$$

:::{.hs}
**HS MEMO**

$$Eu = Ev \Leftrightarrow \langle z, Eu\rangle = \langle z, Ev\rangle \text{ for all }z\in X \Leftrightarrow (Eu)_z = (Ev)_z \text{ for all }z\in X.$$
\begin{align}
(EA_i\hat{x})_z & = \left\langle \rho(z), \sum_{y\in X, (y,x)\in R_i}\rho(y)\right\rangle\\
& = \alpha \langle \rho(z), \rho(x)\rangle\\
& = (\alpha E\hat{x})_z.
\end{align}
Hence, 
$$EA_i\hat{x} = \alpha E\hat{x}.$$
:::

Since $x$ is arbitrary,
$$EA_i = \alpha E.$$
So, 
$$EA_i \in \mathrm{Span} E\; \text{ and }\; EM = \mathrm{Span} E.$$
We have $E\in \mathrm{E_j}$ for unique $j$ $(0\leq j\leq D)$.
:::

:::{.hs}
**HS MEMO**

$$E = \tau_0 E_0 + \cdots + \tau)D E_D, \; \tau_j\in \mathbb{C}\quad (0\leq j\leq D).$$
And, at least one of $\tau_j$ is nonzero, and 
$$\tau_jE_j = EE_j \in \mathrm{Span}E.$$
So, 
$$\tau_jE_j = E$$
as $E_0, \ldots, E_D$ are linearly independent.
:::


Let $Y = (X, \{R_i\}_{0\leq i\leq D})$ be a symmetric scheme, and let $E$ be a primitive idempotent.

:::{.definition #q-poly-representation}
$Y$ is $Q$-polynomial\index{$Q$-polynomial} with respect to $E$, if and only if $Y$ is $Q$-polynomial with respect to some ordering $E_0, E_1, \ldots, E_D$ of primitive idempotents, where $E_0 = |X|^{-1}J$, and $E_1 = E$.
:::

:::{.theorem #balanced}
Assume $Y = (X, \{R_i\}_{0\leq i\leq D})$ is $P$-polynomial (i.e., $(X, R_1)$ is distance-regular). Let $E$ be any primitive idempotent of $Y$. Let $(\rho, H)$ be the corresponding representation.

| $(i)$ The following are equivalent.

| $\quad (ia)$ $Y$ is $Q$-polyonimial with respect to $E$.

| $\quad (ib)$ $(\rho, H)$ is nondegenerate and for all $x,y\in X$, and for all $i,j$ $(0\leq i,j\leq D)$,
$$\sum_{z\in X, (x,z)\in R_i, (y,z)\in R_j}\rho(z) - \sum_{z'\in X, (x,z')\in R_j, (y,z')\in R_i}\rho(z')\in \mathrm{Span}(\rho(x)-\rho(y)).$$

| $\quad (ic)$ $(\rho, H)$ is nondegenerate and for all $x,y\in X$, 
$$\sum_{z\in X, (x,z)\in R_1, (y,z)\in R_2}\rho(z) - \sum_{z'\in X, (x,z')\in R_2, (y,z')\in R_1}\rho(z')\in \mathrm{Span}(\rho(x)-\rho(y)).$$

| $(ii)$ Wirte
$$E = |X|^{-1}\sum_{j=0}^D \theta^*_j A_j,$$
and suppose $(ia)-(ic)$ hold. Then the coefficient in $(ib)$ is
$$p^h_{ij}\frac{\theta_i^*-\theta_j^*}{\theta^*_0-\theta^*_h} \quad (1\leq h\leq D, 0\leq i,j\leq D).$$
:::

:::{.proof}
| $(ia)\to(ib)$ Without loss of generality, assume $E \equiv E_1$, and $Y$ is $Q$-polynomial with respect to $E$.
Then by Lemma \@ref(lem:q-conditions),
$\theta_0^*, \ldots, \theta^*_D$ are distinct. So $\theta^*_h\neq \theta^*_0$ for all $h\in \{1,2\ldots, D\}$, and $(\rho, H)$ is nondegenerate.

Fix $x\in X$, write $E^*_i\equiv E^*_i(x)$, $A^*_i \equiv A^*_i(x)$, $A^* \equiv A_1^*$. 

Let $M$ be the Bose-Mesner algebra. Set
$$L = \{mA^*n - nA^*m\mid m, n\in M\}.$$

Claim 1. $\dim L \leq D$.

_Proof of Claim 1._
\begin{align}
L & = \mathrm{Span}(E_iA^*E_j - E_jA^*E_i \mid 0\leq i<j\leq D)\\
& = \mathrm{Span}(E_iA^*E_{i+1} - E_{i+1}A^*E_i \mid 0\leq i\leq D-1).
\end{align}
Since $E_iA^*E_j = O$ if $q^1_{ij} = 0$ by Lemma \@ref(lem:phijqhij) and Lemma \@ref(lem:vanishing-condition),
and this occurs if $|i-j|>1$ by $Q$-polynomial property.

Hence, $\dim L \leq D$.

Claim 2. $(i)$ $\{A^*A_h - A_hA^*\mid 1\leq h\leq D\}$ is a basis for $L$. In particular,

| $(ii)$ there exist $r^h_{ij}\in \mathbb{C}$ $(1\leq h\leq D, 0\leq i,j\leq D)$ such that
$$A_iA^*A_j - A_jA^*A_i = \sum_{h=1}^D r^h_{ij}(A^*A_h - A_hA^*).$$

_Proof of Claim 2._

| $(i)$ The column $x$ of $A^*A_h - A_hA^*$ is a nonzero scalar $\theta^*_h - \theta^*_0$ times the column $x$ of $A_h$.

:::{.hs}
**HS MEMO**

$$ ((A^*A_h - A_hA^*)\hat{x})_y = E_{xy}(A_h)_{yx}- (A_h)_{yx}E_{xx} = (\theta^*_h-\theta^*_0)(A_h)_{yz}.$$
:::

Also the column $x$ of $A_0, A_1, \ldots, A_D$ are linearly independent.

Hence, the matrices given are linearly independent.

They are in $L$ by construction, so they form a basis for $L$ by Claim 1.

| $(ii)$ This is immediate since
$$A_iA^*A_j - A_jA^*A_i\in L, \quad \text{for all $i,j$}.$$

Cloim 3. 
$$r^\ell_{ij} = p^\ell_{ij}\left(\frac{\theta^*-\theta^*_j}{\theta^*_0 - \theta^*_\ell}\right)\quad (1\leq \ell\leq D, 0\leq i,j\leq D).$$

_Proof of Claim 3._ 
Fix $i,j$,
$$A_iA^*A_j - A_jA^*A_i - \sum_{h=1}^D r^h_{ij}(A^*A_h - A_hA^*) = 0.$$
Pick $\ell$ $(1\leq \ell \leq D)$. Pick $y\in X$ such that $(x,y)\in R_\ell$.
\begin{align}
(A_iA^*A_j)_{xy} & = \sum_{z\in X}(A_i)_{xz}(A^*)_{zz}(A_j)_{zy}\\
& = \sum_{z\in X, (x,z)\in R_i, (y,z)\in R_j}(A^*)_{zz}\\
& = |X|^{-1}p^\ell_{ij}\theta^*_i.
\end{align}
Similarly,
$$(A_jA^*A_i)_{xy} = |X|^{-1}p^\ell_{ij}\theta^*_j.$$
\begin{align}
(A^*A_h-A_hA^*)_{xy} & = (A_0A^*A_h - A_hA^*A_0)_{xy}\\
& = |X|^{-1}p^\ell_{0h}(\theta^*_0 - \theta^*_h)\\
& = \begin{cases}
0 & \text{ if }\; \ell \neq h\\
|X|^{-1}(\theta^*_0-\theta^*_h) & \text{ if } \ell = h.
\end{cases}
\end{align}
Hence,
$$\sum_{h=1}^D r^h_{ij}(A^*A_h - A_hA^*)_{xy} = |X|^{-1}r^\ell_{ij}(\theta^*_0-\theta^*_\ell).$$
Comparing terms, we have
$$p^\ell_{ij}(\theta^*_i-\theta^*_j) - r^\ell_{ij}(\theta^*_0-\theta^*_\ell) = 0.$$

Claim 4. For all $h$ $(1\leq h\leq D)$, for all $i,j$ $(0\leq i,j\leq D)$, for all $w,y\in X$, $(w,y)\in R_h$,
\begin{equation}
\sum_{z\in X,(w,z)\in R_i, (y,z)\in R_j}\rho(z)-\sum_{z'\in X, (w,z')\in R_j, (y,z)\in R_i}\rho(z') - r^h_{ij}(\rho(w)-\rho(y))=0. (\#eq:rhozrhoz)
\end{equation}

_Proof of Claim 4._
Set $L = \langle \mathrm{LHS}$ of \@ref(eq:rhozrhoz), $\rho(x)\rangle$
It suffices to show that $L = 0$.

Note that since $x$ is arbitrary, if $\mathrm{LHS}$ of \@ref(eq:rhozrhoz) is zero.
\begin{align}
L & = \sum_{z\in X,(w,z)\in R_i, (y,z)\in R_j}\langle \rho(z), \rho(x)\rangle -\sum_{z'\in X, (w,z')\in R_j, (y,z)\in R_i}\langle\rho(z'),\rho(x)\rangle \\
& \quad - r^h_{ij}\langle \rho(w)-\rho(y), \rho(x)\rangle\\
& = |X|^{-1}(A_iA^*A_j)_{wy} - |X|^{-1}(A_jA^*A_i)_{wy}-|X|^{-1}\sum_{\ell=1}^Dr^\ell_{ij}(A^*A_\ell - A_\ell A^*)_{wy}\\
& = |X|^{-1} \text{times $wy$ entry of a matrix known to be zero by Claim 2}\\
& = 0.
\end{align}
:::

:::{.hs}
**HS MEMO**

\begin{align}
|X|^{-1}\sum_{\ell=1}^D r^\ell_{ij}(A^*A_\ell - A_\ell A^*)_{wy} & = |X|^{-1}r^h_{ij}(A^*A_h- A_hA^*)_{wy}\\
& = r^h_{ij}(\langle \rho(x),\rho(w)\rangle - \langle \rho(x),\rho(y)\rangle)
\end{align}
:::
