# $P$-and $Q$-Polynomial Schemes {#lec27}
**Friday, April 2, 1993** 

:::{.theorem #p-and-q}
Let $\Gamma = (X,E)$ be a distance-regular graph of diameter $D\geq 3$.

Let $\theta$ denote an eigenvalue of $\Gamma$ with associated primitive idempotent
$$E = \frac{1}{|X|}\sum_{i=0}^D \theta^*_iA_i.$$
Then the following are equivalent.

| $(i)$ $\Gamma$ is $Q$-polynomial with respect to $E$.

| $(ii)$ $\theta^*_0\neq \theta^*_h$ for all $h\in \{1, 2, \ldots, D\}$ and for $i\in \{3, \ldots, D\}$, 
\begin{align}
& c_i\left(\theta^*_2 - \theta^*_i - \frac{(\theta^*_1-\theta^*_{i-1})^2}{\theta^*_0-\theta^*_i}\right) + b_{i-1}\left(\theta^*_2 - \theta^*_{i-1} - \frac{(\theta^*_1-\theta^*_{i})^2}{\theta^*_0-\theta^*_{i-1}}\right)\\
& = (k-\theta)(\theta^*_1+\theta^*_2-\theta^*_{i-1}-\theta^*_i)-(\theta+1)(\theta^*_0-\theta^*_2) (\#eq:cibi1)
\end{align}

| $(iii)$ $\theta^*_0\neq \theta^*_h$ for all $h\in \{1, 2, \ldots, D\}$ and \@ref(eq:cibi1) holds for $i=3$.
:::

:::{.remark}
Note \@ref(eq:cibi1) is trivial for $i = 1, 2$.

$i=1$: 
\begin{align}
\mathrm{LHS} & = \left(\theta^*_2-\theta^*_1 - \frac{\theta^*_1-\theta^*_0)^2}{\theta^*-\theta^*_1}\right)+ k(\theta^*-\theta^*_0)\\
& = \theta^*_2-\theta^*_1 - \theta^*_0 + \theta^*_1 + k(\theta_2^*-\theta^*_0)\\
& = (k+1)(\theta^*_2-\theta^*_0)\\
\mathrm{RHS} & = (k-\theta)(\theta^*_1+\theta^*_2-\theta^*_0-\theta^*_1)-(\theta+1)(\theta^*_0-\theta^*_2)\\
& = (k+1)(\theta^*_2-\theta^*_0).
\end{align}

$i=2$:
\begin{align}
\mathrm{LHS} & = b_1\left(\theta^*_2-\theta^*_1 - \frac{\theta^*_1-\theta^*_0)^2}{\theta^*-\theta^*_1}\right)\\
& = b_1\frac{(\theta^*_2-\theta^*_1)(\theta^*_0-\theta^*_1-\theta^*_2+\theta^*_1)}{\theta^*_0-\theta^*_1}\\
& = b_1\frac{(\theta^*_2-\theta^*_1)(\theta^*_0-\theta^*_2)}{\theta^*_0-\theta^*_1}\\
\mathrm{RHS} & = (\theta+1)(\theta^*_0-\theta^*_2).
\end{align}
Hence,
\begin{align}
\mathrm{LHS}=\mathrm{RHS} & \leftrightarrow b_1\frac{\theta^*_2-\theta^*_1}{\theta^*_0-\theta^*_1} + (\theta + 1) = 0\\
& = b_1(\theta^*_2-\theta^*_1)+(\theta+1)(\theta^*_0-\theta^*_1) = 0.
\end{align}
On the other hand,
\begin{align}
b_1\theta^*_2 + a_1\theta^*_1 + c_1\theta^*_0 & = \theta \theta^*_1\\
b_1\theta^*_1 + a_1\theta^*_1 + c_1\theta^*_1 & = k \theta^*_1,
\end{align}
as $\theta \theta^*_0 = k\theta^*_1$
We have
$$b_1(\theta^*_2 - \theta^*_1) + (\theta^*_0-\theta^*_1) = \theta(\theta^*_1-\theta^*_0).$$
:::

:::{.proof}
Immediate from the proof of Theorem 2.1 in 'A new inequality for distance-regular graphs' [@terwilliger:1995] and Theorem \@ref(thm:balanced).

:::


**Note.** Suppose $(i)-(iii)$ hold. In particular, $\theta^*_0, \theta^*_1, \ldots, \theta^*_D$ are distinct. Then,
$$c_i + a_i + b_i = k\quad (0\leq i\leq D).$$
$$c_i\theta^*_{i-1} + a_i\theta^*_i + b_i\theta^*_{i+1} = \theta \theta^*_j \quad (0\leq i\leq D).$$
$$\frac{\theta^*_i-\theta^*_{i+1}+\theta^*_{i+2}-\theta^*_{i-3}}{\theta^*_{i+1}-\theta^*_{i+2}}\quad \text{is independent of $i$}\quad (0\leq i\leq D-3).$$
\begin{align}
& c_i\left(\theta^*_2 - \theta^*_i - \frac{(\theta^*_1-\theta^*_{i-1})^2}{\theta^*_0-\theta^*_i}\right) + b_{i-1}\left(\theta^*_2 - \theta^*_{i-1} - \frac{(\theta^*_1-\theta^*_{i})^2}{\theta^*_0-\theta^*_{i-1}}\right)\\
& = (k-\theta)(\theta^*_1+\theta^*_2-\theta^*_{i-1}-\theta^*_i)-(\theta+1)(\theta^*_0-\theta^*_2).
\end{align}

Furthermore, we can show for $c_1, \ldots, c_D$, $a_1, \ldots, a_D$, $b_0, b_1, \ldots, b_{D-1}$ in terms of $5$ parameters.

In general, we can take the $5$ parameters to be
$$D, q, s^*, r_1, r_2$$
and get
\begin{align}
b_i & = \frac{h(1-q^{i-D})(1-s^*q^{i+1})(1-r_1q^{i+1})(1-r_2q^{i+1})}{(1-s^*q^{2i+1})(1-s^*q^{2i+2})} \quad (0\leq i\leq D),\\
c_i & = \frac{h(1-q^{i})(1-s^*q^{D+i+1})(r_1-s^*q^{i})(r_2-s^*q^{i})}{s^*q^D(1-s^*q^{2i})(1-s^*q^{2i+1})} \quad (0\leq i\leq D),\\
a_i & = b_0 - c_i - b_i \quad (0\leq i\leq D),
\end{align}
where $h$ variable is chosen so that $c_1 = 1$.

(We must also consider limiting cases $h\to 0$, $s^*\to 0$, $q^*\to \pm 1$.)

See Theorem 2.1 in "The subconstituent algebra of an association scheme, I, II, III, [@terwilliger:1992], [@terwilliger:1993-1], [@terwilliger:1993-2].


:::{.definition #qbinomial}
Let $\Gamma = (X,E)$ be a distance-regular graph of diameter $D\geq 3$. Choose $q \in \mathbb{R}\setminus \{0,-1\}$, set
$$\begin{bmatrix}{i}\\{1}\end{bmatrix} = 1 + q + \cdots + q^{i-1} = \begin{cases} \frac{q^i-1}{q-1} & q\neq 1\\
i & q = 1.\end{cases}$$
:::

:::{.definition #classical}
$\Gamma$ has classical parameters if
\begin{align}
c_i & = \begin{bmatrix}{i}\\{1}\end{bmatrix}\left(1+ \alpha \begin{bmatrix}{i-1}\\{1}\end{bmatrix}\right) (\#eq:ci)\\
b_i & = \left(\begin{bmatrix}{D}\\{1}\end{bmatrix}-\begin{bmatrix}{i}\\{1}\end{bmatrix}\right)\left(\sigma- \alpha \begin{bmatrix}{i}\\{1}\end{bmatrix}\right) (\#eq:bi)
\end{align}
for some $\sigma, \alpha\in \mathbb{R}$.

(This happens for essentially all known families of distance-regular graphs with unbounded diameter, and is essentially equivalent to $s^*=0$.)
:::


:::{.lemma #classical-parameters}
With above notation, suppose \@ref(eq:ci), \@ref(eq:bi) hold.
Then,

| $(i)$ $\theta = \frac{b_1}{q}-1$ is an eigenvalue of $\Gamma$ with $\theta\neq k$.

| $(ii)$ Let $E = |X|^{-1}\sum_{i=0}^D \theta^*_i A_i$ be associated primitive idempotent. Then
$$\frac{\theta^*_i}{\theta^*_0} = 1 + \left(\frac{\theta}{k}-1\right)\begin{bmatrix}{i}\\{1}\end{bmatrix} q^{1-i} \quad (0\leq i\leq D).$$
In particular, $\theta^*_i \neq \theta^*_0$ for all $i\in \{1, 2 \ldots, D\}$.

| $(iii)$ $\Gamma$ is $Q$-polynomial with respect to $E$.
:::

:::{.proof}
| $(i), (ii)$. Need to check
$$c_i\theta^*_{i-1} + a_i\theta^*_i + b_i\theta^*_{i+1} = \theta \theta^*_i \quad (0\leq i\leq D),$$
where $a_i = k-c_i - b_i$ $\quad (0\leq i \leq D)$.

(equivalently: check
\begin{equation}
c_i(\theta^*_{i-1}-\theta^*_i) + b_i(\theta^*_i -\theta^*_{i+1}) = (\theta-k) \theta^*_i \quad (0\leq i\leq D),(\#eq:cibithetak)
\end{equation}
where $c_i, b_i, \theta^*_i, \theta$ are as given.)

:::{.remark}
$$\theta = \frac{b_1}{q}-1, \; \frac{\theta^*_i}{\theta^*_0} = 1 + \left(\frac{\theta}{k}-1\right)\begin{bmatrix}{i}\\{1}\end{bmatrix} q^{1-i}, \; b_0 = \begin{bmatrix}{D}\\{1}\end{bmatrix}\sigma.$$
$i=0$. 
$$\frac{\theta^*_i}{\theta^*_0} = \frac{\theta}{k}, \quad - k\left(1-\frac{\theta^*_1}{\theta^*_0}\right)= -k(1-\frac{\theta}{k}) = \theta -k.$$
$$\frac{\theta^*_{i-1}-\theta^*_i}{\theta^*_0} = \left(\frac{\theta}{k}-1\right)\left(\begin{bmatrix}{i-1}\\{1}\end{bmatrix}q^{2-i}-\begin{bmatrix}{i}\\{1}\end{bmatrix}q^{1-i}\right)=-\left(\frac{\theta}{k}-1\right)q^{1-i}.$$
$$\theta-k=\left(\begin{bmatrix}{D}\\{1}\end{bmatrix}-1\right)(\sigma-\alpha)/q-1 \begin{bmatrix}{D}\\{1}\end{bmatrix}\sigma = \begin{bmatrix}{D-1}\\{1}\end{bmatrix}(\sigma-\alpha)-1-\begin{bmatrix}{D}\\{1}\end{bmatrix}\sigma.$$
\begin{align}
& (c_i(\theta^*_{i-1}-\theta^*_i) + b_i(\theta^*_i -\theta^*_{i+1}) - (\theta-k) \theta^*_i)/\theta^*_0\\
& \quad = -\begin{bmatrix}{i}\\{1}\end{bmatrix}\left(1+\alpha \begin{bmatrix}{i-1}\\{1}\end{bmatrix}\right)\left(\frac{\theta}{k}-1\right)q^{1-i} + \left(\begin{bmatrix}{D}\\{1}\end{bmatrix}-\begin{bmatrix}{i}\\{1}\end{bmatrix}\right)\left(\sigma- \alpha \begin{bmatrix}{i}\\{1}\end{bmatrix}\right)\left(\frac{\theta}{k}-1\right)q^{-i}\\
& \qquad\qquad -(\theta-k)\left(1+\left(\frac{\theta}{k}-1\right)\begin{bmatrix}{i}\\{1}\end{bmatrix}q^{1-i}\right)\\
& \quad = \left(\frac{\theta}{k}-1\right)\left(-\begin{bmatrix}{i}\\{1}\end{bmatrix}\left(1+
\alpha\begin{bmatrix}{i-1}\\{1}\end{bmatrix}\right)q^{1-i}+\begin{bmatrix}{D-i}\\{1}\end{bmatrix}\left(\sigma-\alpha \begin{bmatrix}{i}\\{1}\end{bmatrix}\right)\right.\\
& \qquad\qquad\left.-\left(\begin{bmatrix}{D}\\{1}\end{bmatrix}\sigma +  \left(\begin{bmatrix}{D-1}\\{1}\end{bmatrix}(\sigma-\alpha)-1-\begin{bmatrix}{D}\\{1}\end{bmatrix}\sigma\right)\begin{bmatrix}{i}\\{1}\end{bmatrix}q^{1-i}\right)\right)\\
& \quad = \left(\frac{\theta}{k}-1\right)\left(-\begin{bmatrix}{i}\\{1}\end{bmatrix}q^{1-i}-\alpha\left(\begin{bmatrix}{i}\\{1}\end{bmatrix}\begin{bmatrix}{i-1}\\{1}\end{bmatrix}q^{1-i}+\begin{bmatrix}{D-i}\\{1}\end{bmatrix}\begin{bmatrix}{i}\\{1}\end{bmatrix}-\begin{bmatrix}{D-1}\\{1}\end{bmatrix}\begin{bmatrix}{i}\\{1}\end{bmatrix}q^{1-i}\right)\right.\\
&  \qquad\qquad \left.+\sigma\left(\begin{bmatrix}{D-i}\\{1}\end{bmatrix}-\begin{bmatrix}{D}\\{1}\end{bmatrix}-\begin{bmatrix}{D-1}\\{1}\end{bmatrix}\begin{bmatrix}{i}\\{1}\end{bmatrix}q^{1-i}+\begin{bmatrix}{D}\\{1}\end{bmatrix}\begin{bmatrix}{i}\\{1}\end{bmatrix}q^{1-i}\right)+\begin{bmatrix}{i}\\{1}\end{bmatrix}q^{1-i}\right)
\end{align}
:::

Check $\theta\neq k$. Suppose $\theta = k$. Then
$$\frac{b_1}{q}-1 = k, \; \text{ and }\; q>0.$$
By \@ref(eq:ci), \@ref(eq:bi),
\begin{align}
qc_i - b_i - q(qc_{i-1}-b_{i-1}) & = (k-\theta)q \quad (1\leq i\leq D)\\
& = 0.
\end{align}

:::{.remark}
With the notation of Lemma \@ref(lem:classical-parameters), we have the above equality in general.
\begin{align}
& qc_i-b_i - q(qc_{i-1}-b_{i-1})\\
& \quad = q\begin{bmatrix}{i}\\{1}\end{bmatrix}\left(1+\alpha \begin{bmatrix}{i-1}\\{1}\end{bmatrix}\right)-\left(\begin{bmatrix}{D}\\{1}\end{bmatrix}-\begin{bmatrix}{i}\\{1}\end{bmatrix}\right)\left(\sigma-\alpha\begin{bmatrix}{i}\\{1}\end{bmatrix}\right)\\
& \qquad\qquad -q\left(q\begin{bmatrix}{i-1}\\{1}\end{bmatrix}\left(1+\alpha\begin{bmatrix}{i-2}\\{1}\end{bmatrix}\right)-\left(\begin{bmatrix}{D}\\{1}\end{bmatrix}-\begin{bmatrix}{i-1}\\{1}\end{bmatrix}\right)\left(\sigma-\alpha\begin{bmatrix}{i-1}\\{1}\end{bmatrix}\right)\right)\\
& \quad = \left(q\begin{bmatrix}{i}\\{1}\end{bmatrix}-q^2\begin{bmatrix}{i-1}\\{1}\end{bmatrix}\right) \\
& \qquad\qquad + \alpha\left(q\begin{bmatrix}{i}\\{1}\end{bmatrix}\begin{bmatrix}{i-1}\\{1}\end{bmatrix}+\begin{bmatrix}{D}\\{1}\end{bmatrix}\begin{bmatrix}{i}\\{1}\end{bmatrix}-\begin{bmatrix}{i}\\{1}\end{bmatrix}\begin{bmatrix}{i}\\{1}\end{bmatrix}\right.\\
& \qquad\qquad \left.-q^2\begin{bmatrix}{i-1}\\{1}\end{bmatrix}\begin{bmatrix}{i-2}\\{1}\end{bmatrix}-q\begin{bmatrix}{D}\\{1}\end{bmatrix}\begin{bmatrix}{i-1}\\{1}\end{bmatrix}+q\begin{bmatrix}{i-1}\\{1}\end{bmatrix}\begin{bmatrix}{i-1}\\{1}\end{bmatrix}\right)\\
& \qquad\qquad + \sigma\left(-\begin{bmatrix}{D}\\{1}\end{bmatrix}+\begin{bmatrix}{i}\\{1}\end{bmatrix} + q\begin{bmatrix}{i-1}\\{1}\end{bmatrix}\right)\\
& \quad = q+\alpha\left(-\begin{bmatrix}{i}\\{1}\end{bmatrix}+\begin{bmatrix}{D}\\{1}\end{bmatrix}+q\begin{bmatrix}{i-1}\\{1}\end{bmatrix}\right)+\sigma(q^D-1+1)\\
& \quad = q\left(1 + \begin{bmatrix}{D-1}\\{1}\end{bmatrix}\alpha + q^{D-1}\sigma\right)\\
& \quad = q\left(\begin{bmatrix}{D}\\{1}\end{bmatrix}\sigma - \begin{bmatrix}{D-1}\\{1}\end{bmatrix}\sigma + \begin{bmatrix}{D-1}\\{1}\end{bmatrix}\alpha + 1\right)\\
& \quad = q\left(k-\frac{\begin{bmatrix}{D}\\{1}\end{bmatrix}-1}{q}(\sigma-\alpha)+1\right)\\
& \quad = q(k-\theta).
\end{align}
:::

Hence,
\begin{align}
qc_i - b_i & = q(qc_{i-1}-b_{i-1})\quad (1\leq i\leq D)\\
& = q^i(qc_0 - b_0)\\
& = -q^ik.
\end{align}
If $i = D$, $qc_D = -q^Dk$, $c_D = -q^{D-1}k < 0$, a contradiction.


| $(iii)$ Check the equation $(ii)$ of Theorem \@ref(thm:p-and-q) holds for $i=3$.

:::{.remark}
$\theta^*_0\neq \theta^*_h$ for all $h\in \{1,2,\ldots, D\}$ and 
$$c_3\left(\theta^*_2 - \theta^*_3 - \frac{(\theta^*_1-\theta^*_{2})^2}{\theta^*_0-\theta^*_3}\right) - b_{2} \frac{(\theta^*_1-\theta^*_{3})^2}{\theta^*_0-\theta^*_{2}} = (k-\theta)(\theta^*_1-\theta^*_3)-(\theta+1)(\theta^*_0-\theta^*_2).$$

:::
:::

