# Tridiagonal Pair $A, A^*$ {#lec29}
**Wednesday, April 7, 1993** 

**Introduction to Theorem \@ref(thm:aastar)**

Let $\Gamma = (X,E)$ be distance-regular with diameter $D\geq 3$.

Assume $\Gamma$ is $Q$-polynomial with respect to $E_1$.

Fix a vertex $x\in X$. Write $E^*_i \equiv E^*_i(x)$, $A^*_i \equiv A^*_i(x)$, $A^* = A^*_1$.

We know for $h, i, j$ $(0\leq h, i, j\leq D)$,
\begin{align}
E^*_iA_hE^*_j = O & \leftrightarrow p^h_{ij} = 0\\
E_iA_h^*E_j = O & \leftrightarrow q^h_{ij} = 0.
\end{align}
Also, for $h, i, j$ $(0\leq h, i, j\leq D)$,
\begin{align}
h < |i-j| & \rightarrow p^h_{ij} = 0, \; q^h_{ij} = 0\\
h = |i-j| & \rightarrow p^h_{ij} \neq 0, \; q^h_{ij} \neq 0.
\end{align}

Some $A_h$ (resp. $A^*_h$) is a polynomial of degree exactly $h$ in $A$ (resp. $A^*$), it follows, for $h, i, j$ $(0\leq h, i, j\leq D)$,
$$E^*_iA^hE^*_j, \; E_i{A^*}^hE_j \quad \begin{cases} = 0 & \text{if } h < |i-j|\\
\neq 0 & \text{if } h = |i-j|.\end{cases}$$

We saw that there exist $\beta, \gamma, \delta\in \mathbb{R}$ such that
$$0 = [A, A^2A^*-\beta AA^*A + A^*A^2 - \gamma(AA^*+A^*A) - \delta A^*].$$
In fact, there exist $\beta, \gamma^*, \delta^*\in \mathbb{R}$ such that
$$0 = [A^*, {A^*}^2A-\beta A^*AA^* + A{A^*}^2 - \gamma^*(A^*A+AA^*) - \delta^* A]$$
as well as will will now show.

Let $K$ denote any field. Let $V$ denote any vector space over $K$ of finite positive dimension. Let $\mathrm{End}_K(V)$ denote the $K$-algebra of all $K$-linear transformations $V\to V$.


:::{.theorem #aastar}
Given semi-simple elements $A, A^*\in \mathrm{End}_K(V)$, suppose
\begin{align}
E_i(A^*)^hE_j: & \begin{cases} = 0 & \text{if } h < |i-j|\\
\neq 0 & \text{if } h = |i-j|.\end{cases} \quad (0\leq h,i,j\leq D) (\#eq:eastare)\\
E^*_iA^hE^*_j: & \begin{cases} = 0 & \text{if } h < |i-j|\\
\neq 0 & \text{if } h = |i-j|.\end{cases} \quad (0\leq h,i,j\leq R) (\#eq:estaraestar)
\end{align}
for some ordering $E_0, E_1, \ldots, E_D$ of the primitive idempotents for $A$, and some ordering $E^*_0, E^*_1, \ldots, E^*_R$ of primitive idempotents for $A^*$. Then

| $(i)$ $R = D$.

| $(ii)$ There exist $\beta, \gamma, \gamma^*, \delta, \delta^*\in \mathbb{K}$ such that
\begin{align}
0 & = [A, A^2A^*-\beta AA^*A + A^*A^2 - \gamma(AA^*+A^*A) - \delta A^*]  (\#eq:abracket)\\
& = A^3A^*-A^*A^3 - (\beta+1)(A^2A^*A-AA^*A^2)\\
& \quad -\gamma(A^2A^*-A^*A^2)-\delta(AA^*-A^*A)  (\#eq:aastar)\\
0 & = [A^*, {A^*}^2A-\beta^* A^*AA^* + A{A^*}^2 - \gamma^*(A^*A+AA^*) - \delta^* A]  (\#eq:astarbracket)\\
& = {A^*}^3A - A{A^*}^3 - (\beta+1)({A^*}^2AA^*-A^*A{A^*}^2)\\
& \quad -\gamma^*({A^*}^2A-A{A^*}^2)-\delta^*(A^*A-AA^*).  (\#eq:astara)
\end{align}

| $(iii)$ Let $\theta_i$ (resp. $\theta^*_i$) denote the eigenvalue of $A$ (resp. $A^*$) associated with $E_i$ (resp. $E^*_i$). Then,
\begin{align}
\beta & = \frac{\theta_i-\theta_{i+1}+\theta_{i+2}-\theta_{i+3}}{\theta_{i+1}-\theta_{i+2}} \quad (0\leq i\leq D-3) (\#eq:beta)\\
& = \frac{\theta^*_i-\theta^*_{i+1}+\theta^*_{i+2}-\theta^*_{i+3}}{\theta^*_{i+1}-\theta^*_{i+2}} \quad (0\leq i\leq D-3) (\#eq:betastar)\\
\gamma & = \theta_i - \beta \theta_{i+1} + \theta_{i+2} \quad (0\leq i\leq D-2) (\#eq:gamma1)\\
\gamma^* & = \theta^*_i - \beta \theta^*_{i+1} + \theta^*_{i+2} \quad (0\leq i\leq D-2) (\#eq:gammastar)\\
\delta & = \theta^2_i - \beta \theta_i\theta_{i+1} + \theta^2_{i+1} - \gamma(\theta_i + \theta_{i+1}) \quad (0\leq i\leq D-1) (\#eq:delta)\\
\delta^* & = {\theta^*}^2_i - \beta {\theta^*}_i{\theta^*}_{i+1} + {\theta^*}^2_{i+1} - \gamma^*({\theta^*}_i + {\theta^*}_{i+1}) \quad (0\leq i\leq D-1) (\#eq:deltastar)
\end{align}
In particular, $\beta, \gamma, \gamma^*, \delta, \delta^*$ are uniquely determined by $A$, $A^*$ and the above ordering of ther primitive idempotents, whenever $D\geq 3$.
:::

:::{.proof}

| $(i)$ By symmetry, it suffices to show $D\geq R$. Suppose $R > D$.

Since $A$ is semisimple with exactly $D+1$ distinct eigenvalues, the minimal polynomial of $A$ has degree $D+1$.

Since $R \geq D+1$, 
$$A^R \in \mathrm{Span}\{A^j\mid 0\leq j\leq D\}.$$
Multiplying each term on the left by $E^*_R$ and on the right by $E^*_0$, we find
\begin{equation}
E^*_RA^RE_0^* \in \mathrm{Span}\{E^*_RA^jE^*_0\mid 0\leq j\leq D\}. (\#eq:erstarare0)
\end{equation}
But by \@ref(eq:estaraestar), the left side of \@ref(eq:erstarare0) is nonzero and the right side of \@ref(eq:erstarare0) is $0$, a contradiction.

Hence $D\geq R$.

| $(ii), (iii)$
Recalling the definitions, we have
\begin{align}
A & = \sum_{i=0}^D \theta_i E_i,\\
A^* & = \sum_{i=0}^D \theta_i^* E_i^*,\\
AE_i & = E_iA = \theta_iE_i \quad (0\leq i\leq D),\\
A^*E_i^* & = E_i^*A^* = \theta_i^*E_i^* \quad (0\leq i\leq D).
\end{align}

Claim 1. For all integers $i,j,k,\ell$ $(0\leq i, j, k, \ell\leq D)$ such that $j+k \leq i-\ell$,
\begin{equation}
E^*_iA^jA^*A^kE^*_\ell = \begin{cases} \theta^*_{\ell+k}E^*_iA^{j+k}E^*_\ell & \text{if } j+k = i-l,\\
0 & \text{if } j+k < i-\ell.\end{cases} (\#eq:eistarajastarakestarell)
\end{equation}

_Proof of Claim 1._
The product \@ref(eq:eistarajastarakestarell) eqia;s
$$E^*_iA^j\left(\sum_{h=0}^D \theta_h^* E_h^*\right)A^kE^*_\ell = \sum_{h=0}^D \theta^*_h E^*_iA^jE^*_hA^kE^*_\ell.$$
Now pick any $h$ $(0\leq h\leq D)$, where
$$E^*_iA^jE^*_hA^kE^*_\ell \neq O.$$
Tehn by \@ref(eq:estaraestar), $j\geq |i-h|$, otherwise
$$E^*_iA^jE^*_h = O$$
and by \@ref(eq:eastare), $k\geq |h-\ell|$ otherwise
$$E^*_hA^kE^*_\ell = O.$$
Hence
$$j+k \geq |i-h|+|h-\ell| \geq |i-\ell| \geq i-\ell.$$
Now if $j+k < i-\ell$, we see there is no such $h$, so \@ref(eq:eistarajastarakestarell) holds.

(_Pf._ Suppose $i=j+k+\ell$ with $0\leq i, j, k,\ell, h\leq D$. 

Then $i \geq j, k, \ell$. Since $k = |h-\ell|$, if $h\neq \ell+k$, $h = \ell-k$ and $j - i-h$, 
$\ell-h+i-h = i-\ell$ implies $h=\ell$, $k = 0$ and $h = \ell + k$.)

This proves Claim 1.

Let $M$ denote the subalgebra of $\mathrm{End}_K(V)$ generated by $A$. Observe that $M$ has a basis $E_0, \ldots, E_D$ as a vector space over $K$. Set
$$L:= \mathrm{Span}\{mA^*m-nA^*m \mid m, n\in M\}.$$

Claim 2. $\dim L \leq D$.

_Proof of Claim 2._
Since $E_0, \ldots, E_D$ span $M$, 
\begin{align}
L & = \mathrm{Span}\{E_iA^*E_j - E_jA^*E_i \mid 0\leq i < j \leq D\}\\
& = \mathrm{Span}\{E_{j-1}A^*E_j - E_jA^*E_{j-1} \mid 1\leq j \leq D\}
\end{align}
by \@ref(eq:eastare).

In particular, $L$ has a spanning set of order $D$. 

So, Claim 2 holds.

Claim 3. $\{A^iA^* - A^*A^i\mid 1\leq i\leq D\}$ is a basis for $L$.

_Proof of Claim 3._
Since 
$$A^iA^*-A^*A^i = A^iA^*I - iA^*A^i$$
is contained in $L$ $(1\leq i\leq D)$, and since $\dim L \leq D$, it suffices to show the given elements are linearly independent.

Suppose they are dependent. Then there exists an integer $i$ $(1\leq i\leq D)$ such that 
\begin{equation}
A^iA^*-A^*A^i \in \mathrm{Span}(A^jA^*-A^*A^j\mid 1\leq j < i). (\#eq:aiastarminusastarai)
\end{equation}
Multiplying each term in \@ref(eq:aiastarminusastarai) on the left by $E^*_i$, and on the left by $E^*_0$, and simplifying using
$$E^*_i(A^\ell A^*-A^*A^\ell)E^*_0 = (\theta^*_0-\theta^*_i)E^*_iA^\ell E^*_0,$$
we find
\begin{equation}
E^*_iA^\ell E^*_0 \in \mathrm{Span}(E^*_iA^jE^*_0\mid 1\leq j < i). (\#eq:eistaraiestar0)
\end{equation}
But the left side of \@ref(eq:eistaraiestar0) is nonzero. 

A contradiction.


Since $a^2A^*A-AA^*A^2$ is contained in $L$, we find by Claim 2,
\begin{equation}
A^2A^*A - AA^*A^2 = \sum_{i=1}^D\alpha_i(A^iA^*-A^*A^i) (\#eq:a2astara)
\end{equation}
for some $\alpha_0, \ldots, \alpha_D\in K$.

Claim 4. $\alpha_i = 0 \quad (3<i\leq D)$.

_Proof of Claim 4._
Suppose not, and set
$$t = \max\{i\mid 3<i\leq D, \; \alpha_i\neq 0\}.$$
Then by \@ref(eq:a2astara), and Claim 1,
\begin{align}
0 & = E^*_t\left(A^2A^*A - AA^*A^2 - \sum_{i=1}^D\alpha_i(A^iA^*-A^*A^i)\right)E^*_0\\
& = \alpha_t(\theta^*_t-\theta^*_0)E^*_tA^tE^*_0\\
& \neq O.
\end{align}

(Since $\alpha_i=$ if $i>t$,
\begin{align}
E^*_tA^2A^*AE^*_0 & = E^*_tAA^*A^2E^*_0 = O \quad (\text{as} 2+1 < t-0)\\
E^*_tA^iA^*E^*_0 & = E^*_tA^*A^iE^*_0 = O\\
E^*_tA^tA^*E^*_0 & = \theta^*_0 E^*_tA^tE^*_0,\\
E^*_tA^*A^tE^*_0 & = \theta^*_tE^*_tA^*A^tE^*_0.)\\
\end{align}

A contradiction. This proves Claim 4.

Claim 5.  Suppose $D\geq 3$. Then
\begin{equation}
\alpha_3 = \frac{\theta^*_{i+1}-\theta^*_{i+2}}{\theta^*_i - \theta^*_{i+3}} \quad \text{for all }i, \; (0\leq i\leq D-3). (\#eq:alpha3)
\end{equation}
In particular, $\alpha\neq 0$.

_Proof of Claim 5._
Fix and integer $i$ $(0\leq i\leq D-3$). Then 
by \@ref(eq:eistarajastarakestarell) and \@ref(eq:a2astara),
\begin{align}
O & = E^*_{i+3}\left(A^2A^*A - AA^*A^2 - \sum_{j=1}^3\alpha_j(A^iA^*-A^*A^i)\right)E^*_i\\
& = (\theta^*_{i+1}-\theta^*_{i+2}-\alpha_3(\theta^*_i-\theta^*_{i+3}))E^*_{i+3}A^3E^*_i.
\end{align}
But $E^*_{i+3}A^3E^*_i\neq O$ by \@ref(eq:estaraestar), so \@ref(eq:alpha3) holds.

This proves Claim 5.

Claim 6. Lines \@ref(eq:abracket), \@ref(eq:aastar), \@ref(eq:betastar) hold.

_Proof of Claim 6._
First suppose $D\geq 3$. Then by \@ref(eq:a2astara), Claims 4, and 5,
\begin{equation}
A^22A^*A-AA^*A^2 = \alpha_3(A^3A^*-A^*A^3)+\alpha_2(A^2A^*-A^*A^2) + \alpha_1(AA^*-A^*A), (\#eq:a2astara3)
\end{equation}
where $\alpha_3\neq 0$. Hence
$$A^3A^*-A^*A^3-\frac{1}{\alpha_3}(A^2A^*A-AA^*A^2)+\frac{\alpha_2}{\alpha_3}(A^2A^*-A^*A^2)+
\frac{\alpha_1}{\alpha_3}(AA^*-A^*A)=O.$$
Now \@ref(eq:aastar) is immediate, where
\begin{align}
\beta & = \frac{1}{\alpha_3}-1, (\#eq:beta3)\\
\gamma & = -\frac{\alpha_2}{\alpha_3}, (\#eq:gamma3)\\
\delta & = -\frac{\alpha_1}{\alpha_3}. (\#eq:delta3)
\end{align}
The line \@ref(eq:abracket) follows from the definition of $[\text{ }, \text{ }]$. 

The line \@ref(eq:betastar) is immediate from \@ref(eq:alpha3) and \@ref(eq:beta3).

Now suppose $D < 3$. Then the line \@ref(eq:betastar) is vacuously true, so consider  \@ref(eq:aastar).

Let $\alpha_3$ denote any nonzoro element of $K$.

Then $A^2A^*-A^*A^2, AA^*-A^*A$ certainly span $L$ by Claim 3.

So, \@ref(eq:a2astara3) holds for appropriate $\alpha_1$ and $\alpha_2\in K$.

Now, \@ref(eq:aastar) holds, where $\beta$, $\gamma$, $\delta$ are given by \@ref(eq:beta3), \@ref(eq:gamma3), \@ref(eq:delta3).


Claim 7. Lines \@ref(eq:beta), \@ref(eq:gamma), \@ref(eq:delta) hold.

_Proof of Claim 7._
Pick an integer $i$ $(0\leq i\leq D-1)$.

By \@ref(eq:aastar), we have
\begin{align}
O & = E_i(A^3A^*-A^*A^3-(\beta+1)(A^2A^*A-AA^*A^2)-\gamma(A^2A^*-A^*A^2)-\delta(AA^*-A^*A))E_{i+1}\\
& = E_iA^*E_{i+1}(\theta^3_i-\theta^3-(\beta+1)(\theta^*_i\theta_{i+1}-\theta_i\theta^2)-\gamma(\theta^2_i-\theta^2_{i+1})-\delta(\theta_i-\theta_{i+1}))\\
& = E_iA^*E_{i+1}(\theta_i-\theta_{i+1})(\theta^2_i+\theta_i\theta_{i+1}+\theta_{i+1}^2-(\beta+1)\theta_i\theta_{i+1}-\gamma(\theta_i+\theta_{i+1})-\delta)\\
& = E_iA^*E_{i+1}(\theta_i-\theta_{i+1})(\theta^2_i-\beta\theta_i\theta_{i+1}+\theta_{i+1}^2-\gamma(\theta_i+\theta_{i+1})-\delta).
\end{align}

But $E_iA^*E_{i+1} \neq O$ by \@ref(eq:eastare), and of course, $\theta_i\neq \theta_{i+1}$, so
$$0 = \theta^2_i-\beta\theta_i\theta_{i+1}+\theta_{i+1}^2-\gamma(\theta_i+\theta_{i+1})-\delta.$$
This proves \@ref(eq:delta).

To obtain \@ref(eq:gamma), pick any integer $i$ $(0\leq i\leq D-2)$.
Then by \@ref(eq:delta),
\begin{align}
0 & = \theta^2_i-\beta\theta_i\theta_{i+1}+\theta_{i+1}^2-\gamma(\theta_i+\theta_{i+1})-\delta\\
& \qquad -(\theta^2_{i+1}-\beta\theta_{i+1}\theta_{i+2}+\theta_{i+2}^2-\gamma(\theta_{i+1}+\theta_{i+2})-\delta)\\
& = \theta_i^2 - \beta\theta_i\theta_{i+1}-\gamma\theta_i + \beta\theta_{i+1}\theta_{i+2}-{\theta^*_{i+2}}^2 + \gamma\theta_{i+2}\\
& = (\theta_i-\theta_{i+2})(\theta_i - \beta\theta_{i+1} + \theta_{i+2} - \gamma).
\end{align}
So $0 = \theta_i - \beta\theta_{i+1} + \theta_{i+2} - \gamma$. 

This gives \@ref(eq:gamma).

To see \@ref(eq:beta), pick an integer $i$ $(0\leq i\leq D-3)$.

Then by \@ref(eq:gamma),
\begin{align}
0 & = (\theta_i - \beta\theta_{i+1} + \theta_{i+2} - \gamma) - (\theta_{i+1} - \beta\theta_{i+2} + \theta_{i+3} - \gamma) \\
& = \theta_i-(\beta+1)\theta_{i+1} + (\beta+1)\theta_{i+2} - \theta_{i+3}.
\end{align}
We have
$$\beta = \frac{\theta_i-\theta_{i+3}}{\theta_{i+1}-\theta_{i+2}} - 1 = \frac{\theta_i-\theta_{i+1}+\theta_{i+2}-\theta_{i+3}}{\theta_{i+1}-\theta_{i+2}},$$
as desired.

This proves Claim 7.

We have now proved \@ref(eq:abracket), \@ref(eq:aastar), \@ref(eq:beta), \@ref(eq:betastar), \@ref(eq:gamma1), \@ref(eq:delta).

Interchanging the roles of $A$ and $A^*$, we obtain \@ref(eq:astarbracket), \@ref(eq:astara),  \@ref(eq:gammastar), \@ref(eq:deltastar).
:::
