# Algebra on First Subconstitutent {#lec33}
**Wednesday, April 21, 1993** 

:::{.lemma #mezerostarm}
Let $Y = (X, \{R_i\}_{0\leq i\leq D})$ be a commutative scheme. Fix a vertex $x\in X$, write $E^*_i\equiv E^*_i(x)$, $M^* \equiv M^*(x)$, $T\equiv T(x)$. Then the following hold.

| $(i)$ $E^*_0MM^* = E^*_0M$

| $(ii)$ $E^*_0T = E^*_0M$.

| $(iii)$ $TE^*_0T = ME^*_0M$.

| $(iv)$ $E^*_0E_0E^*_0 = |X|^{-1}E^*_0$.

| $(v)$ $E^*_0E_0E^*_0 = |X|^{-1}E^*_0$.

| $(vi)$ Lines $(i)$-$(iv)$ hold if we interchange $(E_0, E^*_0)$, $(M, M^*)$.

Moreover, $ME^*_0M = M^*E_0M^*$.
:::

:::{.proof}
| $(i)$ $\supseteq$: $1\in M^*$ implies $M\subseteq MM^*$.

$\subseteq$: Pick $\alpha\in E^*_0MM^*$. Show $\alpha\in E^*_0M$. Since $A_0, A_1, \ldots, A_D$ span $M$, and since $E^*_0, E^*_1, \ldots, E^*_D$ span $M^*$, without loss of generality we may assume that 
$$\alpha = E^*_0A_iE^*_j$$
for some $i,j\in \{0, \ldots, D\}$.

Without loss of generality we may assume taht $i = j$, else $\alpha = 0$ by Lemma \@ref(lem:vanishing-condition).

$$(E^*_hA_iE^*_j \neq O \Leftrightarrow p^j_{hi}\neq 0.)$$

Now 
$$\alpha = E^*_0A_i\left(\sum_{h=0}^D E^*_h\right) = E^*_0A_i \in E^*_0M.$$

| $(ii)$ $\supseteq$: This is clear.

$\subseteq$: $E^*_0T$ is the minimal right ideal of $T$ containing $E^*_0$.

So, we just have to show that $E^*_0M$ is a right ideal of $T$ containing $E^*_0$.

It clearly contains $E^*_0$ since $I\in M$, and is a right ideal of $T$ by $(i)$, and the fact that $T$ is generated by $M$ abd $M^*$.

| $(iii)$ By the transpose of $(ii)$,
$$TE^*_0 = ME^*_0,$$
so, 
$$TE^*_0T = (TE^*_0)(E^*_0T) = ME^*_0E^*_0M = ME^*_0M.$$

| $(iv)$ We have
$$E^*_0E_0E^*_0 = \frac{1}{|X|}E^*_0\left(\sum_{h=0}^D A_h\right)E^*_0 = \frac{1}{|X|}E^*_0A_0E^*_0 = |X|^{-1}E^*_0.$$

| $(v)$ The first part is clear by using Lemma \@ref(lem:vanishing-condition) $(ii)$, 
$$E_hA^*_iE_j\neq O \Leftrightarrow q^j_{hi} \neq 0,$$
and Lemma \@ref(lem:phijqhij2) $(iii)$,
$$q^j_{0i} = \delta_{ij}.$$

Also,
$$ME^*_0M = TE^*_0T = TE^*_0E_0E^*_0T \subseteq TE_0T = M^*E_0M^*,$$
and 
$$M^*E_0M^* \subseteq ME^*_0M$$
by dual argument.
So, 
$$M^*E_0M^* = ME^*_0M.$$

This proves the lemma.
:::

:::{.lemma #eonemmstar}
Let $\Gamma = (X, E)$ be distance regular of diameter $D\leq 3$, $Q$-polynomial with respect to $E_0, E_1, \ldots, E_D$. Pick a vertex $x\in X$, 
write $E^*_i\equiv E^*_i(x)$, $M^* \equiv M^*(x)$, $T\equiv T(x)$.

| $(i)$ $E^*_1MM^* = E^*M + E^*_1E_0M^* + E^*_1E_1M^*$.

| $(ii)$ $E_1M^*M = E_1M^* + E_1E^*_0M + E_1E^*_1M$.
:::

:::{.proof}
| $(i)$ View $E^*_{-1}$, $E^*_{D+1}$ as $O$. 

View $\theta^*_{-1}$, $\theta^*_{D+1}$ as indeterminates.

Let $\Delta$ denote $\mathrm{RHS}$ in $(i)$.

$\supseteq$: $I\in M^*$ implies $M\subseteq MM^*$.

$\subseteq$: Suppose not. Then there exists
\begin{equation}
\alpha\in E^*_1MM^*\setminus \Delta. (\#eq:alpha) 
\end{equation}

Since $A_0, A_1, \ldots, A_D$ span $M$, since $E^*_0, E^*_1, \ldots, E^*_D$ span $M^*$, without loss of generality we may assume that
$$\alpha = E^*_1A_iE^*_j$$
for some $i,j\in \{0, \ldots, D\}$.

Observe $|i-j|\leq 1$, else $\alpha =0$ by Lemma \@ref(lem:vanishing-condition).

Without loss of generality, assume $i+j$ is minimal subject to the above constraints.

First assume
\begin{equation}
j = i+1. (\#eq:j)
\end{equation}
Observe
\begin{align}
& E^*_1A_iE^*_{i+1} + E^*_1A_iE^*_i + E^*_1A_iE^*_{i-1}\\
& \qquad = E^*_1A_i\left(\sum_{h=0}^D E^*_h\right)\\
& \qquad = E^*_1A_i\\
& \qquad \in \Delta. (\#eq:icase)
\end{align}

Also, observe
$$E^*_1A_iE^*_i, \; E^*_1A_iE^*_{i-1}\in \Delta$$
by the minimality of $i+j$, so
$$\alpha = E^*_1A_iE^*_{i+1}\in \Delta$$
by \@ref(eq:icase). Hence, \@ref(eq:j) cannot occur.

Since $|i-j|\leq 1$, 
\begin{equation}
i\in \{j, j+1\}. (\#eq:i)
\end{equation}

Observe
\begin{align}
& E^*_1A_{j+1}E^*_{j} + E^*_1A_jE^*_j + E^*_1A_{j-1}E^*_{j}\\
& \qquad = E^*_1\left(\sum_{h=0}^D A_h\right)E^*_j\\
& \qquad = |X|E^*_1E_0E^*_j\\
& \qquad \in \Delta, (\#eq:jplus1)
\end{align}
and
\begin{align}
& \theta^*_{j+1}E^*_1A_{j+1}E^*_{j} + \theta^*_j E^*_1A_jE^*_j + \theta^*_{j-1}E^*_1A_{j-1}E^*_{j}\\
& \qquad = E^*_1\left(\sum_{h=0}^D \theta^*_h A_h\right)E^*_j\\
& \qquad = |X|E^*_1E_1E^*_j\\
& \qquad \in \Delta. (\#eq:thetajplus1)
\end{align}

Since $E^*_1A_{j-1}E^*_j\in \Delta$ by the minimality of $i+j$, so
$$E_1A_{j+1}E^*_j + E^*_1A_jE^*_j \in \Delta,$$
$$\theta^*_{j+1}E^*_1A_{j+1}E^*_{j+1} + \theta^*_jE^*_1A_jE^*_j \in \Delta.$$

But, $\theta^*_0, \theta^*_1, \ldots, \theta^*_D$ are distinct by Lemma \@ref(lem:q-conditions) $(iv)$,
so
$$E^*_1A_{j+1}E^*_j, \; E^*_1A_jE^*_j\in \Delta.$$
But $\alpha$ is one of these two matrices, so
$$\alpha \in \Delta.$$
Hence, \@ref(eq:i) cannot occur either, and we have a contradiction.

| $(ii)$ Dual argument.
:::

:::{.lemma #tildej-tildea}
With the above notation, set
$$\tilde{J}:= E^*_1JE^*_1, \quad \tilde{A}:= E^*_1AE^*_1.$$

| $(i)$ $\tilde{J}^2 = k\tilde{J}$. $(k = \text{valency of $\Gamma$})$

| $(ii)$ $\tilde{J}\tilde{A} = \tilde{A}\tilde{J} = a_1\tilde{J}$. $(a_1 = p^{1}_{11} \text{ for } \Gamma)$

| $(iii)$ $E_1^*E_0E^*_1 = |X|^{-1}\tilde{J}$.

| $(iv)$ $E^*_1E_1E^*_1 = |X|^{-1}(E^*_1(\theta^*_0-\theta^*_2)+\tilde{A}(\theta^*_{1}-\theta^*_2)+\tilde{J}(\theta^*_2))$.
:::

:::{.proof}
| $(i)$ The first subconstituent has $k$ vertices.

| $(ii)$ The first subconstituent is regular of valency $a_1$.

| $(iii)$ Since $E_0 = |X|^{-1}J$, 
$$E^*_1E_0E^*_1 = |X|^{-1}\tilde{J}.$$

| $(iv)$ We have
\begin{align}
E^*_1E_1E^*_1 & = E^*_1\left(|X|^{-1}\sum_{h=0}^D\theta^*_h A_h\right)E^*_1\\
& = |X|^{-1}(\theta^*_0E^*_1A_0E^*_1 + \theta^*_1E^*_1A_1E^*_1 + \theta^*_2E^*_1A_2E^*_1)\\
& = |X|^{-1}(\theta^*_0E^*_1 + \theta^*_1\tilde{A} + \theta^*_2E^*_1A_2E^*_1). (\#eq:e1stare1e1star)
\end{align}
Also,
\begin{align}
\tilde{J} & = E^*_1JE^*_1\\
& = E^*_1A_0E^*_1 + E^*_1A_1E^*_1 + E^*_1A_2E^*_1\\
& = E^*_1 + \tilde{A} + E^*_1A_2E^*_1. (\#eq:tildej)
\end{align}
Eliminating the $E^*_1A_2E^*_1$ term in \@ref(eq:e1stare1e1star) using equation \@ref(eq:tildej), we get $(iv)$.
:::


:::{.lemma #e1starte1star}
With the above notation,

| $(i)$ $E^*_1T = E^*_1E_0M^* + E^*_1M + E^*_1E_1M^* + E^*_1E_1E^*_1M + \cdots$.

| $(ii)$ $E^*_1TE^*_1 = \mathrm{Span}(E^*_1E_0E^*_1, E^*_1, E^*_1E_1E^*_1, (E^*_1E_1E^*_1)^2, \ldots)$.

| $(iii)$ $E^*_1TE^*_1 = \mathrm{Span}(\tilde{J}, E^*_1, \tilde{A}, \tilde{A}^2, \ldots )$.

| $(iv)$ $E^*_1TE^*_1$ is symmetric (in particular, commutative).
:::


:::{.proof}
| $(i)$ $\supseteq$: Clear.

$\subseteq$: $E^*_1T$ is the minimal right ideal of $\Gamma$ that contains $E^*_1$.

$\mathrm{RHS}$ contains $E^*_1$, so show $\mathrm{RHS}$ is a right ideal of $T$.

Show $\mathrm{RHS}$ is closed with respect to multiplication on right by $M$, $M^*$.

We have
$$E^*_1E_0M^*(M) = E^*_1E_0M^*, \; E^*_1E_0M^*(M^*) = E^*_1E_0M^*$$
by dual of Lemma \@ref(lem:mezerostarm) $(i)$.

By Lemma \@ref(lem:eonemmstar),
\begin{align}
& E^*_1E_1E^*_1\cdots E^*_1M(M^*)\\
& \qquad = E^*_1E_1E^*_1\cdots E_1(E^*_1MM^*)\\
& \qquad = E^*_1E_1E^*_1\cdots E_1(E^*_1M+E^*_1E_0M^* + E^*_1E_1M^*)\\
& \qquad \in \mathrm{RHS},
\end{align}
because
$$E^*_1E_1E^*_1\cdots E_1E^*_1E_0M^* \subseteq E^*_1TE_0T = E^*_1M^*E_0M^* = E^*_1E_0M^*.$$

By Lemma \@ref(lem:eonemmstar),
\begin{align}
& E^*_1E_1E^*_1\cdots E_1M^*(M)\\
& \qquad = E^*_1E_1E^*_1\cdots E^*_1(_1M^*M)\\
& \qquad = E^*_1E_1E^*_1\cdots E^*_1(E_1M^*+E_1E^*_0M^* + E_1E^*_1M)\\
& \qquad \in \mathrm{RHS},
\end{align}
because by the last part of Lemma \@ref(lem:mezerostarm),
$$E^*_1E_1E^*_1\cdots E^*_1E_1E^*_0M \subseteq E^*_1TE^*_0T = E^*_1ME^*_0M = E^*_1E_0M^*.$$

| $(ii)$ Multiply $(i)$ on the right by $E^*_1$, we have

\begin{align}
E^*_1TE^*_1 & = E^*_1E_0M^*E^*_1 + E^*_1ME^*_1 + E^*_1E_1M^*E^*_1\\
& \quad + \cdots + E^*_1E_1\cdots E_1M^*E^*_1 + E^*_1E_1\cdots E^*_1ME^*_1\\
& = \mathrm{Span}(E^*_1E_0E^*_1, E^*_1, E^*_1E_1E^*_1, (E^*_1E_1E^*_1)^2, \ldots).
\end{align}

:::{.hs}
**HS MEMO**

Note that by Lemma \@ref(thm:aastar),
\begin{align}
E^*_1ME^*_1 & = \mathrm{Span}(E^*_1A_0E^*_1, E^*_1A_1E^*_1, E^*_1A_2E^*_1)\\
& = \mathrm{Span}(E^*_1, E^*_1E_1E^*_1, E^*_1E_0E^*_1).
\end{align}
Moreover, 
$$E^*_1\cdots E^*_1E_0E^*_1 \subseteq E^*_1TE_0TE^*_1 = E^*_1M^*E_0M^*E^*_1 \in \mathrm{Span}(E^*_1E_0E^*_1).$$
:::

| $(iii)$ By $(ii)$, $E^*_1TE^*_1$ is generated by $\tilde{J} = |X|E^*_1E_0E^*_1$ and $E^*_1E_1E^*_1$.

By Lemma \@ref(lem:tildej-tildea) $(iv)$, $E^*_1TE^*_1$ is generated by $\tilde{J}, \tilde{A}$.

But, $\mathrm{Span}{\tilde{J}}$ is a $2$-sided ideal by Lemma \@ref(lem:tildej-tildea) $(i)$, $(ii)$. 

Hence, we have $(iii)$.

| $(iv)$ $\tilde{A}$, $\tilde{J}$ are symmetric commuting matrices, we have the claim.
:::
