# Structure of 1-Thin DRG  {#lec40}
**Friday, May 7, 1993** 

:::{.lemma #endpoint-at-most-one}
With the above notation, let $W$ denota a thin irreducible $T$-module of endpoint $0$ or $1$. Pick $0\neq v\in E^*_1V$. Then the following hold.

| $(i)$ Eigenvalue for $\tilde{J}$ is $0$ if $r(W)=1$, and $k$ if $r(W) = 0$.

| $(ii)$ Eigenvalue for $E^*_1$ is $1$ if $r(W)=1$, and $1$ if $r(W) = 0$.

| $(iii)$ Eigenvalue for $\tilde{A}$ is $a_0(W)$ if $r(W)=1$, and $a_1$ if $r(W) = 0$.

| $(iv)$ Eigenvalue for $A^+$ is $a^+(W) = \frac{\gamma_1}{c_2}-1-\Psi$ if $r(W)=1$, and $\frac{a_2}{c_2}-\Psi$ if $r(W) = 0$.

| $(v)$ Eigenvalue for $A^-$ is $a^-(W) = a_0(W)\left(\frac{\gamma_1}{c_2}-1-2\Psi\right)-\frac{a_2}{c_2}$ if $r(W)=1$,

where 
$$\gamma_0 = 1+a_0(W), \text{ and } \gamma_1 = \frac{c_2b_2\gamma_0}{b_1+\gamma_0(a_1+2-c_2)-\gamma^2_0}$$
as in Theorem \@ref(lem:thin-endpoint1). (The eigenvalue for $A^-$ on $v$ will be discussed later in this lecture.)
:::

:::{.proof}
| $(i)-(iii)$ Clear.

| $(iv)$ We have
\begin{align}
A^+ & = R^{-1}E^*_2A_2E^*_1 - \Psi E^*_1,\\
A_2 & = \frac{A^2-a_1A - kI}{c_2},\\
E^*_2A_2E^*_1 & = E^*_2\left(\frac{A^2-a_1A - kI}{c_2}\right)E^*_1\\
& = \frac{1}{c_2}(RF + FR - a_1R)E^*_1.
\end{align}

If $r(W) = 1$,
\begin{align}
A^+v & = \frac{1}{c_2}(R^{-1}RFv + R^{-1}FRv - a_1R^{-1}Rv) - \Psi v\\
& = \frac{1}{c_2}(R^{-1}Ra_0(W)v + R^{-1}a_1(W)Rv - a_1R^{-1}Rv) - \Psi v\\
& = \frac{1}{c_2}\left(a_0(W) + a_1(W) - a_1) - \Psi\right)v.
\end{align}
But, 
$$a_1(W) = \gamma_1 - \gamma_0 + a_1 + 1 - c_2, \quad \gamma_0 = a_0(W) + 1$$
by Theorem \@ref(thm:endpoint1).

So,
\begin{align}
A^+v & = \left(\frac{1}{c_2}(a_0(W) + \gamma_1 - \gamma_0 + a_1 + 1 - c_2 - a_1) - \Psi)\right)v\\
& = \left(\frac{\gamma_1}{c_2}-1-\Psi\right)v.
\end{align}

If $r(W) = 0$, 
\begin{align}
A^+v & = \frac{1}{c_2}(R^{-1}RFv + R^{-1}FRv - a_1R^{-1}Rv) - \Psi v\\
& = \frac{1}{c_2}(R^{-1}Ra_1v + R^{-1}a_2Rv - a_1R^{-1}Rv) - \Psi v\\
& = \left(\frac{a_2}{c_2}-\Psi\right)v.
\end{align}

| $(v)$ Immediate from $(iv)$, and 
$$A^- = \tilde{A}A^+ - \left(\frac{a_2}{c_2} - \Psi\right)E^*_1 + \Psi(\tilde{J}-\tilde{A}-E^*_1).$$

:::{.hs}
**HS MEMO**

If $r(W) =1$,
\begin{align}
A^-v & = \left(a_0(W)\left(\frac{\gamma_1}{c_2}-1-\Psi\right) - \left(\frac{c_2}{a_2}-\Psi\right) + \Psi(-a_0(W)-1)\right) v\\
& = \left(a_0(W)\left(\frac{\gamma_1}{c_2}-1-2\Psi\right) - \frac{c_2}{a_2}\right)v.
\end{align}
If $r(W) = 0$,
\begin{align}
A^-v & = \left(a_1\left(\frac{a_2}{c_2}-\Psi\right) - \left(\frac{a_2}{c_2}-\Psi\right) + \Psi(k-a_1-1)\right) v\\
& = \left((a_1-1)\frac{a_2}{c_2}+ (k-2a_1)\Psi\right)v.
\end{align}
:::

This completes the proof.
:::

Let $W_1, W_2, W_3, W_4$ denote $4$ possible isomorphism classes of $T$-modules of endpoint $1$. Then $a_0(W_1), a_0(W_2), a_0(W_3), a_0(W_4)$ are roots of a fourth degree polynomial whose coefficients are determined from intersection numbers of $\Gamma$.

So, $a_0(W_1), a_0(W_2), a_0(W_3), a_0(W_4)$ are determined by intersection numbers.

Let $\widetilde{m_i}$ denote the multiplicity of $W_i$ $(1\leq i\leq 4$), which is equal to the multiplicity of $a_0(W)$ as eigenvalue $1$ of $\tilde{A}|_{(E^*_1V)_{new}}$.

:::{.lemma #tilde-mi}
With the above notation, we have the following.

| $(i)$ $\tilde{m}_1$, $\tilde{m}_2$, $\tilde{m}_3$, $\tilde{m}_4$ are determined from intersection numbers and $\Psi$.

| $(ii)$ $\tilde{m}_i$ is independent of vertex $x$. $(1\leq i\leq 4)$.

| $(iii)$ $\ell:= \dim E^*_1TE^*_1$ is independent of $x$.
:::


:::{.proof}
| $(i)$ Let $e_i\in E^*_1TE^*_1$ $(1\leq i\leq 4)$ denote the orthogonal projection on to the maximal eigenspace of $(E^*_1V)_{new}$ corresponding to $\lambda_i$. ($e=0$ if and only if $\lambda_i$ does not appear.) Set
$$e_0 = \frac{1}{k}\tilde{J}.$$
Then eigenvalues for each $e_1, e_1, e_3, e_4$ are as follows.
$$\begin{array}{|c|ccccc|} \hline
\text{} & e_0 & e_1 & e_2 & e_3 & e_4\\
\hline
\tilde{J} & k & 0 & 0 & 0 & 0\\
E^*_1 & 1 & 1 & 1 & 1 & 1 \\
\tilde{A} & a_1 & a_0(W_1) & a_0(W_2) & a_0(W_3) & a_0(W_4)\\
A^+ & \frac{a_2}{c_2}-\Psi & a^+(W_1)  & a^+(W_2)  & a^+(W_3)  & a^+(W_4)\\
A^- & \star & a^-(W_1)  & a^-(W_2)  & a^-(W_3)  & a^-(W_4)\\
\hline
\end{array}$$

Observe that $e^2_i = e_i$, $\mathrm{trace} \:e_i = \mathrm{rank}\:e_i = \tilde{m}_i$ $(1\leq i\leq 4)$, and $\mathrm{trace}\: e_0 = \mathrm{rank}\:e_0 = 1$.

By taking the trace of $\tilde{J}, E^*_1, \tilde{A}, A^+, A^-$, we have
\begin{align}
k & = k,\\
k & = 1 + \tilde{m}_1 + \tilde{m}_2 + \tilde{m}_3 + \tilde{m}_4,\\
0 & = a_1 + a_0(W_1)\tilde{m}_1 + a_0(W_2)\tilde{m}_2 + a_0(W_3)\tilde{m}_3 + a_0(W_4)\tilde{m}_4,\\
0 & = \left(\frac{a_2}{c_2}-\Psi\right) + a^+(W_1)\tilde{m}_1 + a^+(W_2)\tilde{m}_2 + a^+(W_3)\tilde{m}_3 + a^+(W_4)\tilde{m}_4,\\
0 & = \left(\star\right) + a^-(W_1)\tilde{m}_1 + a^-(W_2)\tilde{m}_2 + a^-(W_3)\tilde{m}_3 + a^-(W_4)\tilde{m}_4.
\end{align}

The coefficient matrix for $\tilde{m}_1,\tilde{m}_2, \tilde{m}_3,\tilde{m}_4$ is nonsingular (this is what you need to check and show).

:::{.hs}
**HS MEMO**

Complutation is not completed.
:::

| $(ii)$ $\Psi$ is independent of base vertex $x$.

| $(iii)$ We have
\begin{align}
\dim E^*_1TE^*_1 & = |\{i\mid 1\leq i\leq 4, \; e_i\neq 0\}| + 1\\
& = |\{i\mid 1\leq i\leq 4, \; \tilde{m}_i\neq 0\}| + 1.
\end{align}

This completes the proof of the lemma.
:::


Let $\Gamma = (X, E)$ be thin distance regular of diameter $D\geq 5$, and $Q$-polynomial with respect to $E_0, E_1, \ldots, E_D$.

Fix vertices $x,y\in X$ with $\partial(x,y) = 1$,
$$E^*_{ij} \equiv E^*_i(x)E^*_j(y), \quad \delta_{ij} = E^*_{ij}\delta.$$
We saw 
$$T(x)\hat{y} = T(y)\hat{x}.$$
Hence, 
$$H := T(x)\hat{y} = T(y)\hat{x}$$
is a $T(x,y)$ module.
$T(x,y) \subseteq \mathrm{Mat}_X(\mathbb{C})$ is generated by $M$, $M^*(x)$, $M^*(y)$.

:::{.lemma #h}
With the above notation, we have the following.

| $(i)$ $E^*_{i,i+1}H = \mathrm{Span}(\delta_{i,i+1}) \quad (0\leq i\leq D-1)$.

| $(ii)$ $E^*_{i+1,i}H = \mathrm{Span}(\delta_{i+1,i}) \quad (0\leq i\leq D-1)$.

| $(iii)$ $E^*_{i,i}H = \ell-2 \leq 3 \quad (1\leq i\leq D-1)$.
:::

:::{.proof}
| $(i)$ $\supseteq$: We have
$$\delta_{i,i+1} = E^*_iA_{i+1}\hat{y} \in T(x)\hat{y} = H.$$

| $\subseteq$: Pick $h\in E^*_{i,i+1}H$. Then $h = R^{i-1}v$, where $v = (R^{-1})^{i-1}h\in E^*_1V$.

So, $v\in \mathrm{Span}(\delta_{12}, \delta_{11}, \delta_{10}, \delta^+_{11}, \delta^-_{11})$.

:::{.hs}
**HS MEMO**

\begin{align}
v &\in E^*_1V \cap T(x)\hat{y}\\
& = E^*_1T(x)E^*_1\hat{y}\\
& = \mathrm{Span}(\tilde{J}, E^*_1, \tilde{A}, A^+, A^-)\hat{y}\\
& = \mathrm{Span}(\delta_{10}+ \delta_{11}+ \delta_{12}, \delta_{10}, \delta_{11}, \delta^+_{11}, \delta^-_{11})\\
& = \mathrm{Span}(\delta_{10}, \delta_{11},  \delta_{12}, \delta^+_{11}, \delta^-_{11}).
\end{align}
:::

Hence, there exists $\alpha \in \mathbb{C}$ such that
$$v-\alpha \delta_{12}  \in \mathrm{Span}(\delta_{10}, \delta_{11}, \delta^+_{11}, \delta^-_{11}) = E^*_{11}H + E^*_{10}H.$$
So,
$$v-\alpha(\delta_{12} + \delta_{11} + \delta_{10}) \in E^*_{11}H + E^*_{10}H.$$
\begin{align}
E^*_{ii}H + E^*_{i,i-1}H & \ni R^{i-1}(v-\alpha(\delta_{12}+\delta_{11}+\delta_{10}))\\
& = h - \alpha'(\delta_{i,i+1}+\delta_{ii}+\delta_{i,i-1}).
\end{align}
Hence, 
$$h-\alpha'\delta_{i,i+1}\in (E^*_{ii}H + E^*_{i,i-1}H)\cap E^*_{i,i+1}H.$$
Thus,
$$h = \alpha'\delta_{i,i+1} \in \mathrm{Span}(\delta_{i,i+1}).$$

| $(ii)$ By symmetry, we have the assertion.

| $(iii)$ $E^*_i H = E^*_{i,i+1}H + E^*_{i,i}H + E^*_{i,i-1}H$, and $\dim E^*_iH = \ell$, $\dim E^*_{i,i+1}H =1$, and $\dim E^*_{i,i-1}H = 1$.
Hence, $\dim E^*_{i,i}H = \ell -2$.
:::

:::{.hs}
**HS MEMO**

Since $H = T(x)\hat{y} \subseteq T(x)E^*_{1}(x)V$, and
$$(R^{-1})^{i-1}: E^*_iH \to E^*_1H$$
is one-to-one and onto if $i\leq D$.
:::


:::{.theorem #zi}
Let $\Gamma = (X, E)$ be thin distance regular of diameter $D\geq 5$, and $Q$-polynomial with respect to $E_0, E_1, \ldots, E_D$.

Pick $i$ $(2\leq i\leq D)$, and pick $x, y, z\in X$ such that $\partial(x,y) =1$, $\partial(y,z) = i-1$, $\partial(x,z) = i$.

Then,
$$z_i = |\{w\mid w\in W, \partial(x,w) =1, \partial(y,w)=1, \partial(z,w)=i-1\}|$$
is independent of $x, y, z$.
:::

:::{.proof}
Observe that $z_i$ is the $zx$ entry in 
$$\Delta = E^*_{i-1}(y)A_{i-1}E^*_1(y)AE^*_1(y)$$
as
$$\Delta \hat{x} = \sum_{z\in X, \partial(x,z)=i, \partial(y,z)=i-1}z_i(x,y,z)\hat{z}.$$
Hence, $z_i(x,y,z)$ is independent of $z$. 

So, $z_i(x,y,z)$ is determined  by intersection numbers and $\Psi = \Psi(x,y)$, which is independent of $x, y$ as well.
:::
