# Comparison Table {#table}

We list Definitions, Theorems, Lemmas, etc. with the numbers in the original handwritten note.

| Chapter | New Numbering                                       | Old Numbering  |
|----------------|-------------------------|-----------------------|
| 1       | Example \@ref(exm:four-vertex-graph)                | Example        |
|         | Example \@ref(exm:adjacency-matrix)                 | Example        |
|         | Definition \@ref(def:regular)                       | Definition     |
|         | Lemma \@ref(lem:largestev)                          | Lemma 1        |
|         | Definition \@ref(def:path)                          | Definition     |
|         | Definition \@ref(def:distance)                      | Definition     |
|         | Definition \@ref(def:connected)                     | Definition     |
|         | Definition \@ref(def:diameter)                      | Definition     |
|         | Definition \@ref(def:t-algebra)                     | Definition     |
|         | Definition \@ref(def:module)                        | Definition     |
|         | Lemma \@ref(lem:complete-reducibility)              | Lemma 2        |
| 2       | Definition \@ref(def:reducible)                     | Definition     |
|         | Definition \@ref(def:bipartite-mat)                 | Definition     |
|         | Theorem \@ref(thm:pf)                               | Theorem 3      |
|         | Lemma \@ref(lem:pfl)                                | Lemma 4        |
|         | Definition \@ref(def:bipartite)                     | Definition     |
|         | Corollary \@ref(cor:spec)                           | Corollary 5    |
| 3       | Definition \@ref(def:isom)                          | Definition     |
|         | Definition \@ref(def:auto)                          | Definition     |
|         | Definition \@ref(def:transitive)                    | Definition     |
|         | Definition \@ref(def:cayley)                        | Definition     |
|         | Example \@ref(exm:cyclic6)                          | Example        |
|         | Example \@ref(exm:k6minus1)                         | Example        |
|         | Example \@ref(exm:d6)                               | Example        |
|         | Theorem \@ref(thm:cayley-graph)                     | Theorem 6      |
|         | Definition \@ref(def:character)                     | Definition     |
|         | Example \@ref(exm:cyclic3)                          | Example        |
|         | Lemma \@ref(lem:charactergroup)                     | Lemma 7        |
| 4       | Theorem \@ref(thm:charcter-group)                   | Theorem 8      |
|         | Example \@ref(exm:character-cyclic6)                | Example        |
|         | Example \@ref(exm:hd2)                              | Example        |
|         | Definition \@ref(def:rd)                            | Definition     |
|         | Lemma \@ref(lem:irreducible)                        | Lemma 9        |
| 5       | Definition \@ref(def:isomorphic-modules)            | Definition     |
|         | Theorem \@ref(thm:hd2-modules)                      | Theorem 10     |
| 6       | Theorem \@ref(thm:hd2-modules2)                     | Theorem 11     |
|         | Definition \@ref(def:thin-dualthin)                 | Definition     |
|         | Definition \@ref(def:q-polynomial-graph)            | Definition     |
| 7       | Definition \@ref(def:johnson)                       | Definition     |
|         | Example \@ref(exm:j42)                              | Example        |
|         | Lemma \@ref(lem:ev-johnson)                         | Lemma 12       |
|         | Theorem \@ref(thm:thin-condition)                   | Theorem 13     |
| 8       | Lemma \@ref(lem:property-g)                         | Lemma 14       |
| 9       | Lemma \@ref(lem:thin-module-structure)              | Lemma 15       |
|         | Corollary \@ref(cor:thin-is-dualthin)               | Corollary 16   |
|         | Lemma \@ref(lem:measure-wi)                         | Lemma 17       |
|         | Definiton \@ref(def:measure)                        | Definition     |
| 10      | Lemma \@ref(lem:orthogonality)                      | Lemma 18       |
|         | Lemma \@ref(lem:determined-by-m)                    | Lemma 19       |
|         | Corollary \@ref(cor:isomorphic)                     | Corollary 20   |
| 11      | Lemma \@ref(lem:principal-module)                   | Lemma 21       |
|         | Lemma \@ref(lem:baiparite-principal)                | Lemma 22       |
| 12      | Lemma \@ref(lem:distance-reguarity)                 | Lemma 23       |
|         | Theorem \@ref(thm:two-thin-modules)                 | Theorem 24     |
| 13      | Lemma \@ref(lem:two-principal-modules)              | Lemma 25       |
|         | Theorem \@ref(thm:distance-regular-x)               | Theorem 26     |
|         | Proposition \@ref(prp:dim-diameter)                 | Proposition 27 |
| 14      | Lemma \@ref(lem:basic-data)                         | Lemma 28       |
|         | Lemma \@ref(lem:thin-endpoint1)                     | Lemma 29       |
| 15      | Definition \@ref(def:complete-graph)                | Definition     |
|         | Lemma \@ref(lem:sedond-and-largest-ev)              | Lemma 30       |
| 16      | Definition \@ref(def:ith-incidence)                 | Definition     |
|         | Lemma \@ref(lem:incidence-matrices)                 | Lemma 31       |
|         | Theorem \@ref(thm:endpoint1)                        | Theorem 32     |
|         | Lemma \@ref(lem:aixigi)                             | Lemma 33\*     |
| 17      | Definition \@ref(def:association-scheme)            | Definition     |
|         | Definition \@ref(def:incidencemat-of-as)            | Definition     |
|         | Example \@ref(exm:dr)                               | Example 1      |
|         | Example \@ref(exm:gen-tr)                           | Example 2      |
|         | Exercise \@ref(exr:gen-tr-case)                     | Exercise       |
|         | Example \@ref(exm:centralizer-alg)                  | Example 3      |
| 18      | Lemma \@ref(lem:dr-scheme)                          | Lemma 33       |
| 19      | Lemma \@ref(lem:ei)                                 | Lemma 34       |
|         | Definition \@ref(def:dual-bose-mesner)              | Definition:    |
| 20      | Lemma \@ref(lem:pij-qij)                            | Lemma 34-a     |
|         | Lemma \@ref(lem:phijqhij)                           | Lemma 34-b     |
|         | Lemma \@ref(lem:vanishing-condition)                | Lemma 35       |
|         | Corollary \@ref(cor:qhij)                           | Corollary 36   |
|         | Lemma \@ref(lem:vector-function-product)            | Lemma 37       |
| 21      | Lemma \@ref(lem:norton-algebra)                     | Lemma 38       |
|         | Lemma \@ref(lem:autom-of-norton-algebra)            | Lemma 39       |
| 22      | Lemma \@ref(lem:phijqhij2)                          | Lemma 40       |
|         | Definition \@ref(def:q-polynomial)                  | Definition     |
|         | Lemma \@ref(lem:q-conditions)                       | Lemma 41       |
| 23      | Theorem \@ref(thm:q-polynomial-space)               | Theorem 42     |
|         | Definition \@ref(def:representation-of-y)           | Definition     |
|         | Example \@ref(exm:representation-of-hd2)            | Example        |
| 24      | Definition \@ref(def:equivalence-of-representation) | Definition     |
|         | Lemma \@ref(lem:rep-of-scheme)                      | Lemma 43       |
|         | Definition \@ref(def:q-poly-representation)         | Definition     |
|         | Theorem \@ref(thm:balanced)                         | Theorem 44     |
| 26      | Corollary \@ref(cor:beta)                           | Corollary 45   |
|         | Lemma \@ref(lem:dual-eigenvalues)                   | Lemma 46       |
| 27      | Theorem \@ref(thm:p-and-q)                          | Theorem 47     |
|         | Definition \@ref(def:qbinomial)                     | Definition     |
|         | Definition \@ref(def:classical)                     | Definition     |
|         | Lemma \@ref(lem:classical-parameters)               | Lemma 48       |
|         | Example \@ref(exm:classical-parameters)             | Example        |
| 28      | Lemma \@ref(lem:EV)                                 | Lemma 49       |
|         | Conjecture \@ref(cnj:EV)                            | Conjecture     |
| 29      | Theorem \@ref(thm:aastar)                           | Theorem 50     |
| 30      | Theorem \@ref(thm:rfl-relations)                    | Theorem 51     |
|         | Lemma \@ref(lem:epm-gpm)                            | Lemma 52       |
|         | Corollary \@ref(cor:fr2lr2r2l)                      | Corollary 53   |
| 31      | Lemma \@ref(lem:inverse-of-r)                       | Lemma 54       |
| 32      | Lemma \@ref(lem:action-of-r)                        | Lemma 55       |
|         | Lemma \@ref(lem:action-on-estar1v-new)              | Lemma 56       |
|         | Lemma \@ref(lem:generator-endpoint1-mod)            | Lemma 57       |
| 33      | Lemma \@ref(lem:mezerostarm)                        | Lemma 58       |
|         | Lemma \@ref(lem:eonemmstar)                         | Lemma 59       |
|         | Lemma \@ref(lem:tildej-tildea)                      | Lemma 60       |
|         | Lemma \@ref(lem:e1starte1star)                      | Lemma 61       |
| 34      | Lemma \@ref(lem:mvplusmstarvstar)                   | Lemma 62       |
|         | Lemma \@ref(lem:tv)                                 | Lemma 63       |
|         | Lemma \@ref(lem:tv-thin)                            | Lemma 64       |
| 35      | Theorem \@ref(thm:dim5)                             | Theorem 65     |
| 36      | Conjecture \@ref(cnj:q-polynomial)                  | Conjecture     |
|         | Conjecture \@ref(cnj:unimodality)                   | Conjecture     |
|         | Conjecture \@ref(cnj:not-thin)                      | Conjecture     |
| 37      | Lemma \@ref(lem:1-thin-condition)                   | Lemma 66       |
|         | Definition \@ref(def:generalized-adjacency-matrix)  | Definition     |
|         | Example \@ref(exm:generalized-adjacecy-matrix)      | Example        |
|         | Lemma \@ref(lem:generalized-adjacecy-matrix)        | Lemma 67       |
| 38      | Lemma \@ref(lem:e11star-to-e22star)                 | Lemma 68       |
|         | Definition \@ref(def:Psi)                           | Definition     |
|         | Lemma \@ref(lem:map-e11star-to-e22star)             | Lemma 69       |
| 39      | Lemma \@ref(lem:delta-minus11)                      | Lemma 70       |
|         | Lemma \@ref(lem:psi)                                | Lemma 71       |
|         | Lemma \@ref(lem:aplus-aminus)                       | Lemma 72       |
|         | Lemma \@ref(lem:tyx-equals-txy)                     | Lemma 73       |
| 40      | Lemma \@ref(lem:endpoint-at-most-one)               | Lemma 74       |
|         | Lemma \@ref(lem:tilde-mi)                           | Lemma 75       |
|         | Lemma \@ref(lem:h)                                  | Lemma 76       |
|         | Theorem \@ref(thm:zi)                               | Theorem 77     |
|         |                                                     |                |
